#!/usr/bin/env python3
"""
National BPS Carbon Fines Calculator
=====================================
Calculates carbon emissions reduction and fine avoidance for commercial buildings
in cities with Building Performance Standards (BPS).

METHODOLOGY: Calculates emissions from RAW ENERGY DATA (kBtu) using city-specific
emission factors, NOT from pre-calculated emissions column.

ODCV is applied PER FUEL TYPE based on HVAC percentages:
  net_fuel = fuel × (1 - hvac_pct × odcv_pct)

Author: Generated by Claude
Date: 2025-12-01
"""

import pandas as pd
import numpy as np
import re
import os
import shutil
from pathlib import Path
from datetime import datetime

BACKUP_DIR = '/Users/forrestmiller/Desktop/nationwide-prospector/BACKUPS_GO_HERE/csv_backups'

def create_backup(input_file):
    """Create timestamped backup before any changes."""
    Path(BACKUP_DIR).mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    backup_path = f"{BACKUP_DIR}/portfolio_data_backup_{timestamp}.csv"
    shutil.copy(input_file, backup_path)
    print(f"Backup created: {backup_path}")
    return backup_path

def safe_float(val, default=0.0):
    """Convert value to float, returning default if NaN or None."""
    if val is None:
        return default
    try:
        f = float(val)
        if np.isnan(f):
            return default
        return f
    except (ValueError, TypeError):
        return default

# =============================================================================
# CONFIGURATION
# =============================================================================

INPUT_CSVS = [
    "/Users/forrestmiller/Desktop/nationwide-prospector/data/source/portfolio_data.csv",
]

# Default HVAC percentages if not in CSV
DEFAULT_ELEC_HVAC = 0.45
DEFAULT_GAS_HVAC = 0.85
DEFAULT_STEAM_HVAC = 0.90

# Zip code to city lookup for edge cases
ZIP_TO_CITY = {
    '92108': 'San Diego',
    '91302': 'Calabasas',
}

# =============================================================================
# EMISSION FACTORS BY CITY (tCO2e per kBtu)
# =============================================================================

# NYC LL97 factors (2024-2029 period)
NYC_FACTORS = {
    'electricity': 0.0000847,   # tCO2e/kBtu (0.000288962 / 3.412)
    'gas': 0.00005311,          # tCO2e/kBtu
    'steam': 0.00004493,        # tCO2e/kBtu
}

# Boston BERDO factors
BOSTON_FACTORS = {
    'electricity': 0.000085,    # tCO2e/kBtu
    'gas': 0.00005311,          # tCO2e/kBtu
    'steam': 0.0000664,         # tCO2e/kBtu
}

# Cambridge BEUDO factors (same grid as Boston - EPA eGRID NEWE)
CAMBRIDGE_FACTORS = {
    'electricity': 0.000085,    # tCO2e/kBtu (same as Boston)
    'gas': 0.00005311,          # tCO2e/kBtu
    'steam': 0.0000664,         # tCO2e/kBtu
}

# DC BEPS - Not emissions-based, uses Energy Star score
# Using standard factors for carbon reduction calc only
DC_FACTORS = {
    'electricity': 0.000288,    # tCO2e/kBtu (using NYC as proxy)
    'gas': 0.000053,            # tCO2e/kBtu
    'steam': 0.00004493,        # tCO2e/kBtu
}

# Denver - EUI-based, not emissions-based
# Using standard factors for carbon reduction calc only
DENVER_FACTORS = {
    'electricity': 0.000288,    # tCO2e/kBtu (using NYC as proxy)
    'gas': 0.000053,            # tCO2e/kBtu
    'steam': 0.00004493,        # tCO2e/kBtu
}

# Seattle BEPS factors - Very clean grid (hydropower)
SEATTLE_FACTORS = {
    'electricity': 0.0000029,   # tCO2e/kBtu
    'gas': 0.000053,            # tCO2e/kBtu
    'steam': 0.000081,          # tCO2e/kBtu
}

# St. Louis - EUI-based
# Using standard factors for carbon reduction calc only
STLOUIS_FACTORS = {
    'electricity': 0.000288,    # tCO2e/kBtu (using NYC as proxy)
    'gas': 0.000053,            # tCO2e/kBtu
    'steam': 0.00004493,        # tCO2e/kBtu
}

# =============================================================================
# BPS LAW PARAMETERS
# =============================================================================

BPS_LAWS = {
    'New York': {
        'loc_state': 'NY',
        'law_name': 'Local Law 97 (LL97)',
        'type': 'emission',
        'fine_rate': 268,  # $/tCO2e
        'emission_cap': 0.00758,  # tCO2e/sqft (2024-2029)
        'min_sqft': 25000,
        'factors': NYC_FACTORS,
    },
    'Boston': {
        'loc_state': 'MA',
        'law_name': 'BERDO 2.0',
        'type': 'emission',
        'fine_rate': 234,  # $/tCO2e
        'emission_cap': 0.0053,  # tCO2e/sqft (5.3 kgCO2e = 0.0053 tCO2e)
        'min_sqft': 20000,
        'factors': BOSTON_FACTORS,
    },
    'Cambridge': {
        'loc_state': 'MA',
        'law_name': 'Cambridge BEUDO',
        'type': 'emission',
        'fine_rate': 234,  # $/tCO2e (same ACP as Boston)
        'emission_cap': 0.0053,  # tCO2e/sqft (same as Boston)
        'min_sqft': 25000,
        'factors': CAMBRIDGE_FACTORS,
    },
    'Washington': {
        'loc_state': 'DC',
        'law_name': 'DC BEPS',
        'type': 'energy_star',
        'fine_rate': 10,  # $/sqft
        'max_fine': 7500000,
        'min_sqft': 50000,
        'factors': DC_FACTORS,
    },
    'Denver': {
        'loc_state': 'CO',
        'law_name': 'Energize Denver',
        'type': 'eui',
        'fine_rate': 0.30,  # $/kBtu over target
        'eui_target': 48.3,  # kBtu/sqft
        'min_sqft': 25000,
        'factors': DENVER_FACTORS,
    },
    'Seattle': {
        'loc_state': 'WA',
        'law_name': 'Seattle BEPS',
        'type': 'emission',
        'fine_rate': 10,  # $/sqft per 5-year cycle
        'emission_cap': 0.00081,  # tCO2e/sqft (0.81 kgCO2e = 0.00081 tCO2e)
        'min_sqft': 20000,
        'cycle_years': 5,
        'factors': SEATTLE_FACTORS,
    },
    'San Francisco': {
        'loc_state': 'CA',
        'law_name': 'EBEPO',
        'type': 'none',  # No emission caps yet
        'min_sqft': 10000,
    },
    'St. Louis': {
        'loc_state': 'MO',
        'law_name': 'St. Louis BEPS',
        'type': 'eui',
        'fine_rate': 500,  # $/day if non-compliant
        'eui_target': 71.7,  # kBtu/sqft
        'min_sqft': 50000,
        'factors': STLOUIS_FACTORS,
    },
}

# =============================================================================
# CITY EXTRACTION FUNCTION
# =============================================================================

def extract_city(address, state):
    """Extract city from address string."""
    if not address:
        return None

    address = ' '.join(address.split())
    address = re.sub(r',\s*,', ',', address)

    if not state:
        match = re.search(r',\s*([A-Z]{2})\s+\d{5}', address)
        if match:
            state = match.group(1)
        else:
            match = re.search(r',\s*([A-Z]{2}),?\s*\d{5}', address)
            if match:
                state = match.group(1)

    if not state:
        return None

    parts = [p.strip() for p in address.split(',') if p.strip()]

    for i, part in enumerate(parts):
        if re.match(rf'^{state}\s*\d*', part, re.IGNORECASE) or part.upper() == state:
            if i > 0:
                city = parts[i-1]
                if not re.match(r'^[\d\s]+$', city):
                    return city

    match = re.search(rf'([A-Za-z\s\.]+)\s+{state}\s+\d{{5}}', address, re.IGNORECASE)
    if match:
        city = match.group(1).strip()
        city = re.sub(r'^(Suite|Ste|Bldg|Building|Floor|Fl)\s*\d+\s*', '', city, flags=re.IGNORECASE).strip()
        if city and not re.match(r'^[\d\s]+$', city):
            return city

    if state == 'CO':
        for part in parts:
            if re.match(r'^802\d{2}$', part.strip()):
                return 'Denver'

    for part in parts:
        zip_match = re.search(r'\d{5}', part)
        if zip_match:
            zip_code = zip_match.group()
            if zip_code in ZIP_TO_CITY:
                return ZIP_TO_CITY[zip_code]

    return None

# =============================================================================
# EMISSIONS CALCULATION (from raw energy data)
# =============================================================================

def calc_emissions_from_energy(elec_kbtu, gas_kbtu, steam_kbtu, factors):
    """Calculate emissions from raw energy data using emission factors."""
    emissions = (
        elec_kbtu * factors['electricity'] +
        gas_kbtu * factors['gas'] +
        steam_kbtu * factors['steam']
    )
    return emissions

def apply_odcv_to_energy(elec_kbtu, gas_kbtu, steam_kbtu, odcv_pct, elec_hvac, gas_hvac, steam_hvac):
    """Apply ODCV reductions per fuel type based on HVAC percentages.

    Key: If energy is 0, the HVAC % doesn't matter - reduction is 0.
    This handles NaN in HVAC % when the corresponding energy is 0/NaN.
    """
    # Calculate reductions (only if energy exists)
    elec_reduction = elec_kbtu * elec_hvac * odcv_pct if elec_kbtu > 0 else 0
    gas_reduction = gas_kbtu * gas_hvac * odcv_pct if gas_kbtu > 0 else 0
    steam_reduction = steam_kbtu * steam_hvac * odcv_pct if steam_kbtu > 0 else 0

    net_elec = elec_kbtu - elec_reduction
    net_gas = gas_kbtu - gas_reduction
    net_steam = steam_kbtu - steam_reduction

    return net_elec, net_gas, net_steam


def calc_energy_reduction(elec_kbtu, gas_kbtu, steam_kbtu, odcv_pct, elec_hvac, gas_hvac, steam_hvac):
    """Calculate total energy reduction in kBtu from ODCV.

    Returns the sum of reductions across all fuel types, handling NaN properly.
    """
    elec_reduction = elec_kbtu * elec_hvac * odcv_pct if elec_kbtu > 0 else 0
    gas_reduction = gas_kbtu * gas_hvac * odcv_pct if gas_kbtu > 0 else 0
    steam_reduction = steam_kbtu * steam_hvac * odcv_pct if steam_kbtu > 0 else 0

    return elec_reduction + gas_reduction + steam_reduction

# =============================================================================
# FINE AVOIDANCE CALCULATION FUNCTIONS
# =============================================================================

def calc_fine_nyc(row):
    """NYC Local Law 97 - Emission-based, $268/tCO2e over cap."""
    params = BPS_LAWS['New York']
    factors = params['factors']

    # Use safe_float to handle NaN properly
    sqft = safe_float(row.get('bldg_sqft'), 0)
    elec = safe_float(row.get('energy_elec_kbtu'), 0)
    gas = safe_float(row.get('energy_gas_kbtu'), 0)
    steam = safe_float(row.get('energy_steam_kbtu'), 0)
    odcv_pct = safe_float(row.get('odcv_hvac_savings_pct'), 0)

    # HVAC percentages - use default only if energy exists but pct is NaN
    elec_hvac = safe_float(row.get('hvac_pct_elec'), DEFAULT_ELEC_HVAC) if elec > 0 else 0
    gas_hvac = safe_float(row.get('hvac_pct_gas'), DEFAULT_GAS_HVAC) if gas > 0 else 0
    steam_hvac = safe_float(row.get('hvac_pct_steam'), DEFAULT_STEAM_HVAC) if steam > 0 else 0

    if sqft < params['min_sqft']:
        return 0, 0, 0

    # Baseline emissions
    baseline_emissions = calc_emissions_from_energy(elec, gas, steam, factors)

    # With ODCV emissions
    net_elec, net_gas, net_steam = apply_odcv_to_energy(
        elec, gas, steam, odcv_pct, elec_hvac, gas_hvac, steam_hvac
    )
    with_odcv_emissions = calc_emissions_from_energy(net_elec, net_gas, net_steam, factors)

    # Carbon reduction
    carbon_reduction = baseline_emissions - with_odcv_emissions

    # Fine calculation
    cap = sqft * params['emission_cap']
    baseline_overage = max(0, baseline_emissions - cap)
    with_odcv_overage = max(0, with_odcv_emissions - cap)

    baseline_fine = baseline_overage * params['fine_rate']
    post_odcv_fine = with_odcv_overage * params['fine_rate']

    return carbon_reduction, baseline_fine, post_odcv_fine


def calc_fine_boston(row):
    """Boston BERDO - Emission-based, $234/tCO2e over cap."""
    params = BPS_LAWS['Boston']
    factors = params['factors']

    # Use safe_float to handle NaN properly
    sqft = safe_float(row.get('bldg_sqft'), 0)
    elec = safe_float(row.get('energy_elec_kbtu'), 0)
    gas = safe_float(row.get('energy_gas_kbtu'), 0)
    steam = safe_float(row.get('energy_steam_kbtu'), 0)
    odcv_pct = safe_float(row.get('odcv_hvac_savings_pct'), 0)

    # HVAC percentages - use default only if energy exists but pct is NaN
    elec_hvac = safe_float(row.get('hvac_pct_elec'), DEFAULT_ELEC_HVAC) if elec > 0 else 0
    gas_hvac = safe_float(row.get('hvac_pct_gas'), DEFAULT_GAS_HVAC) if gas > 0 else 0
    steam_hvac = safe_float(row.get('hvac_pct_steam'), DEFAULT_STEAM_HVAC) if steam > 0 else 0

    if sqft < params['min_sqft']:
        return 0, 0, 0

    # Baseline emissions
    baseline_emissions = calc_emissions_from_energy(elec, gas, steam, factors)

    # With ODCV emissions
    net_elec, net_gas, net_steam = apply_odcv_to_energy(
        elec, gas, steam, odcv_pct, elec_hvac, gas_hvac, steam_hvac
    )
    with_odcv_emissions = calc_emissions_from_energy(net_elec, net_gas, net_steam, factors)

    # Carbon reduction
    carbon_reduction = baseline_emissions - with_odcv_emissions

    # Fine calculation (cap is in tCO2e/sqft)
    cap = sqft * params['emission_cap']
    baseline_overage = max(0, baseline_emissions - cap)
    with_odcv_overage = max(0, with_odcv_emissions - cap)

    baseline_fine = baseline_overage * params['fine_rate']
    post_odcv_fine = with_odcv_overage * params['fine_rate']

    return carbon_reduction, baseline_fine, post_odcv_fine


def calc_fine_cambridge(row):
    """Cambridge BEUDO - Emission-based, $234/tCO2e over cap (same as Boston)."""
    params = BPS_LAWS['Cambridge']
    factors = params['factors']

    # Use safe_float to handle NaN properly
    sqft = safe_float(row.get('bldg_sqft'), 0)
    elec = safe_float(row.get('energy_elec_kbtu'), 0)
    gas = safe_float(row.get('energy_gas_kbtu'), 0)
    steam = safe_float(row.get('energy_steam_kbtu'), 0)
    odcv_pct = safe_float(row.get('odcv_hvac_savings_pct'), 0)

    # HVAC percentages - use default only if energy exists but pct is NaN
    elec_hvac = safe_float(row.get('hvac_pct_elec'), DEFAULT_ELEC_HVAC) if elec > 0 else 0
    gas_hvac = safe_float(row.get('hvac_pct_gas'), DEFAULT_GAS_HVAC) if gas > 0 else 0
    steam_hvac = safe_float(row.get('hvac_pct_steam'), DEFAULT_STEAM_HVAC) if steam > 0 else 0

    if sqft < params['min_sqft']:
        return 0, 0, 0

    # Baseline emissions
    baseline_emissions = calc_emissions_from_energy(elec, gas, steam, factors)

    # With ODCV emissions
    net_elec, net_gas, net_steam = apply_odcv_to_energy(
        elec, gas, steam, odcv_pct, elec_hvac, gas_hvac, steam_hvac
    )
    with_odcv_emissions = calc_emissions_from_energy(net_elec, net_gas, net_steam, factors)

    # Carbon reduction
    carbon_reduction = baseline_emissions - with_odcv_emissions

    # Fine calculation (cap is in tCO2e/sqft)
    cap = sqft * params['emission_cap']
    baseline_overage = max(0, baseline_emissions - cap)
    with_odcv_overage = max(0, with_odcv_emissions - cap)

    baseline_fine = baseline_overage * params['fine_rate']
    post_odcv_fine = with_odcv_overage * params['fine_rate']

    return carbon_reduction, baseline_fine, post_odcv_fine


def calc_fine_dc(row):
    """DC BEPS - ENERGY STAR-based, $10/sqft prorated.

    Since we don't have ENERGY STAR scores, estimate based on emissions reduction.
    """
    params = BPS_LAWS['Washington']
    factors = params['factors']

    # Use safe_float to handle NaN properly
    sqft = safe_float(row.get('bldg_sqft'), 0)
    elec = safe_float(row.get('energy_elec_kbtu'), 0)
    gas = safe_float(row.get('energy_gas_kbtu'), 0)
    steam = safe_float(row.get('energy_steam_kbtu'), 0)
    odcv_pct = safe_float(row.get('odcv_hvac_savings_pct'), 0)

    # HVAC percentages - use default only if energy exists but pct is NaN
    elec_hvac = safe_float(row.get('hvac_pct_elec'), DEFAULT_ELEC_HVAC) if elec > 0 else 0
    gas_hvac = safe_float(row.get('hvac_pct_gas'), DEFAULT_GAS_HVAC) if gas > 0 else 0
    steam_hvac = safe_float(row.get('hvac_pct_steam'), DEFAULT_STEAM_HVAC) if steam > 0 else 0

    if sqft < params['min_sqft']:
        return 0, 0, 0

    # Calculate carbon reduction
    baseline_emissions = calc_emissions_from_energy(elec, gas, steam, factors)
    net_elec, net_gas, net_steam = apply_odcv_to_energy(
        elec, gas, steam, odcv_pct, elec_hvac, gas_hvac, steam_hvac
    )
    with_odcv_emissions = calc_emissions_from_energy(net_elec, net_gas, net_steam, factors)
    carbon_reduction = baseline_emissions - with_odcv_emissions

    # DC BEPS fine estimate: energy reduction improves ENERGY STAR score
    # Assume energy reduction % translates to proportional fine reduction
    # Conservative: only 30% of theoretical max fine avoided
    energy_reduction_pct = odcv_pct * elec_hvac  # Approximate

    # Baseline fine = full theoretical fine (prorated based on score gap)
    # Post-ODCV fine = baseline minus avoided amount
    max_fine = sqft * params['fine_rate']
    baseline_fine = min(max_fine * 0.5, params['max_fine'])  # Assume 50% of max as baseline
    fine_avoidance = max_fine * energy_reduction_pct * 0.3
    fine_avoidance = min(fine_avoidance, params['max_fine'])
    post_odcv_fine = max(0, baseline_fine - fine_avoidance)

    return carbon_reduction, baseline_fine, post_odcv_fine


def calc_fine_denver(row):
    """Denver Energize - EUI-based, $0.30/kBtu over target."""
    params = BPS_LAWS['Denver']
    factors = params['factors']

    # Use safe_float to handle NaN properly
    sqft = safe_float(row.get('bldg_sqft'), 0)
    site_eui = safe_float(row.get('energy_site_eui'), 0)
    elec = safe_float(row.get('energy_elec_kbtu'), 0)
    gas = safe_float(row.get('energy_gas_kbtu'), 0)
    steam = safe_float(row.get('energy_steam_kbtu'), 0)
    odcv_pct = safe_float(row.get('odcv_hvac_savings_pct'), 0)

    # HVAC percentages - use default only if energy exists but pct is NaN
    elec_hvac = safe_float(row.get('hvac_pct_elec'), DEFAULT_ELEC_HVAC) if elec > 0 else 0
    gas_hvac = safe_float(row.get('hvac_pct_gas'), DEFAULT_GAS_HVAC) if gas > 0 else 0
    steam_hvac = safe_float(row.get('hvac_pct_steam'), DEFAULT_STEAM_HVAC) if steam > 0 else 0

    if sqft < params['min_sqft']:
        return 0, 0, 0

    # Calculate carbon reduction
    baseline_emissions = calc_emissions_from_energy(elec, gas, steam, factors)
    net_elec, net_gas, net_steam = apply_odcv_to_energy(
        elec, gas, steam, odcv_pct, elec_hvac, gas_hvac, steam_hvac
    )
    with_odcv_emissions = calc_emissions_from_energy(net_elec, net_gas, net_steam, factors)
    carbon_reduction = baseline_emissions - with_odcv_emissions

    # Denver fine is EUI-based
    target_eui = params['eui_target']

    # Calculate total energy reduction from ODCV (handles NaN properly)
    energy_reduction = calc_energy_reduction(
        elec, gas, steam, odcv_pct, elec_hvac, gas_hvac, steam_hvac
    )

    # Calculate baseline and with-ODCV EUI
    baseline_eui = site_eui
    if sqft > 0:
        eui_reduction = energy_reduction / sqft
        with_odcv_eui = max(0, baseline_eui - eui_reduction)
    else:
        with_odcv_eui = baseline_eui

    # Fine calculation
    baseline_overage_kbtu = max(0, baseline_eui - target_eui) * sqft
    with_odcv_overage_kbtu = max(0, with_odcv_eui - target_eui) * sqft

    baseline_fine = baseline_overage_kbtu * params['fine_rate']
    post_odcv_fine = with_odcv_overage_kbtu * params['fine_rate']

    return carbon_reduction, baseline_fine, post_odcv_fine


def calc_fine_seattle(row):
    """Seattle BEPS - Emission-based, $10/sqft if over cap (per 5-year cycle)."""
    params = BPS_LAWS['Seattle']
    factors = params['factors']

    # Use safe_float to handle NaN properly
    sqft = safe_float(row.get('bldg_sqft'), 0)
    elec = safe_float(row.get('energy_elec_kbtu'), 0)
    gas = safe_float(row.get('energy_gas_kbtu'), 0)
    steam = safe_float(row.get('energy_steam_kbtu'), 0)
    odcv_pct = safe_float(row.get('odcv_hvac_savings_pct'), 0)

    # HVAC percentages - use default only if energy exists but pct is NaN
    elec_hvac = safe_float(row.get('hvac_pct_elec'), DEFAULT_ELEC_HVAC) if elec > 0 else 0
    gas_hvac = safe_float(row.get('hvac_pct_gas'), DEFAULT_GAS_HVAC) if gas > 0 else 0
    steam_hvac = safe_float(row.get('hvac_pct_steam'), DEFAULT_STEAM_HVAC) if steam > 0 else 0

    if sqft < params['min_sqft'] or sqft == 0:
        return 0, 0, 0

    # Baseline emissions using Seattle's emission factors
    baseline_emissions = calc_emissions_from_energy(elec, gas, steam, factors)

    # With ODCV emissions
    net_elec, net_gas, net_steam = apply_odcv_to_energy(
        elec, gas, steam, odcv_pct, elec_hvac, gas_hvac, steam_hvac
    )
    with_odcv_emissions = calc_emissions_from_energy(net_elec, net_gas, net_steam, factors)

    # Carbon reduction
    carbon_reduction = baseline_emissions - with_odcv_emissions

    # Check compliance (emissions per sqft vs cap)
    baseline_intensity = baseline_emissions / sqft
    with_odcv_intensity = with_odcv_emissions / sqft
    cap = params['emission_cap']

    baseline_over_cap = baseline_intensity > cap
    with_odcv_over_cap = with_odcv_intensity > cap

    # Seattle fine is binary: $10/sqft per 5-year cycle if over cap
    annual_fine = sqft * params['fine_rate'] / params['cycle_years']

    # Baseline fine: full fine if over cap, 0 if compliant
    baseline_fine = annual_fine if baseline_over_cap else 0
    # Post-ODCV fine: full fine if still over cap, 0 if compliant
    post_odcv_fine = annual_fine if with_odcv_over_cap else 0

    return carbon_reduction, baseline_fine, post_odcv_fine


def calc_fine_sf(row):
    """San Francisco EBEPO - No emission caps yet."""
    factors = NYC_FACTORS  # Use standard factors for carbon calc

    # Use safe_float to handle NaN properly
    elec = safe_float(row.get('energy_elec_kbtu'), 0)
    gas = safe_float(row.get('energy_gas_kbtu'), 0)
    steam = safe_float(row.get('energy_steam_kbtu'), 0)
    odcv_pct = safe_float(row.get('odcv_hvac_savings_pct'), 0)

    # HVAC percentages - use default only if energy exists but pct is NaN
    elec_hvac = safe_float(row.get('hvac_pct_elec'), DEFAULT_ELEC_HVAC) if elec > 0 else 0
    gas_hvac = safe_float(row.get('hvac_pct_gas'), DEFAULT_GAS_HVAC) if gas > 0 else 0
    steam_hvac = safe_float(row.get('hvac_pct_steam'), DEFAULT_STEAM_HVAC) if steam > 0 else 0

    # Calculate carbon reduction only
    baseline_emissions = calc_emissions_from_energy(elec, gas, steam, factors)
    net_elec, net_gas, net_steam = apply_odcv_to_energy(
        elec, gas, steam, odcv_pct, elec_hvac, gas_hvac, steam_hvac
    )
    with_odcv_emissions = calc_emissions_from_energy(net_elec, net_gas, net_steam, factors)
    carbon_reduction = baseline_emissions - with_odcv_emissions

    return carbon_reduction, 0, 0  # No fines - no caps


def calc_fine_stlouis(row):
    """St. Louis BEPS - EUI-based, $500/day if non-compliant."""
    params = BPS_LAWS['St. Louis']
    factors = params['factors']

    # Use safe_float to handle NaN properly
    sqft = safe_float(row.get('bldg_sqft'), 0)
    site_eui = safe_float(row.get('energy_site_eui'), 0)
    elec = safe_float(row.get('energy_elec_kbtu'), 0)
    gas = safe_float(row.get('energy_gas_kbtu'), 0)
    steam = safe_float(row.get('energy_steam_kbtu'), 0)
    odcv_pct = safe_float(row.get('odcv_hvac_savings_pct'), 0)

    # HVAC percentages - use default only if energy exists but pct is NaN
    elec_hvac = safe_float(row.get('hvac_pct_elec'), DEFAULT_ELEC_HVAC) if elec > 0 else 0
    gas_hvac = safe_float(row.get('hvac_pct_gas'), DEFAULT_GAS_HVAC) if gas > 0 else 0
    steam_hvac = safe_float(row.get('hvac_pct_steam'), DEFAULT_STEAM_HVAC) if steam > 0 else 0

    if sqft < params['min_sqft']:
        return 0, 0, 0

    # Calculate carbon reduction
    baseline_emissions = calc_emissions_from_energy(elec, gas, steam, factors)
    net_elec, net_gas, net_steam = apply_odcv_to_energy(
        elec, gas, steam, odcv_pct, elec_hvac, gas_hvac, steam_hvac
    )
    with_odcv_emissions = calc_emissions_from_energy(net_elec, net_gas, net_steam, factors)
    carbon_reduction = baseline_emissions - with_odcv_emissions

    # St. Louis fine is binary - compliant or not
    target_eui = params['eui_target']

    # Calculate total energy reduction from ODCV (handles NaN properly)
    energy_reduction = calc_energy_reduction(
        elec, gas, steam, odcv_pct, elec_hvac, gas_hvac, steam_hvac
    )

    baseline_eui = site_eui
    if sqft > 0:
        eui_reduction = energy_reduction / sqft
        with_odcv_eui = max(0, baseline_eui - eui_reduction)
    else:
        with_odcv_eui = baseline_eui

    baseline_compliant = baseline_eui <= target_eui
    with_odcv_compliant = with_odcv_eui <= target_eui

    # St. Louis fine is binary: $500/day ($182,500/yr) if non-compliant
    annual_fine = params['fine_rate'] * 365  # $500/day * 365

    # Baseline fine: full fine if non-compliant, 0 if compliant
    baseline_fine = annual_fine if not baseline_compliant else 0
    # Post-ODCV fine: full fine if still non-compliant, 0 if compliant
    post_odcv_fine = annual_fine if not with_odcv_compliant else 0

    return carbon_reduction, baseline_fine, post_odcv_fine


def calc_non_bps(row):
    """Non-BPS cities - calculate carbon reduction only."""
    factors = NYC_FACTORS  # Use standard factors

    # Use safe_float to handle NaN properly
    elec = safe_float(row.get('energy_elec_kbtu'), 0)
    gas = safe_float(row.get('energy_gas_kbtu'), 0)
    steam = safe_float(row.get('energy_steam_kbtu'), 0)
    odcv_pct = safe_float(row.get('odcv_hvac_savings_pct'), 0)

    # HVAC percentages - use default only if energy exists but pct is NaN
    elec_hvac = safe_float(row.get('hvac_pct_elec'), DEFAULT_ELEC_HVAC) if elec > 0 else 0
    gas_hvac = safe_float(row.get('hvac_pct_gas'), DEFAULT_GAS_HVAC) if gas > 0 else 0
    steam_hvac = safe_float(row.get('hvac_pct_steam'), DEFAULT_STEAM_HVAC) if steam > 0 else 0

    baseline_emissions = calc_emissions_from_energy(elec, gas, steam, factors)
    net_elec, net_gas, net_steam = apply_odcv_to_energy(
        elec, gas, steam, odcv_pct, elec_hvac, gas_hvac, steam_hvac
    )
    with_odcv_emissions = calc_emissions_from_energy(net_elec, net_gas, net_steam, factors)
    carbon_reduction = baseline_emissions - with_odcv_emissions

    return carbon_reduction, 0, 0  # No BPS law, no fines


# Map cities to their calculation functions
FINE_CALCULATORS = {
    'New York': calc_fine_nyc,
    'Boston': calc_fine_boston,
    'Cambridge': calc_fine_cambridge,
    'Washington': calc_fine_dc,
    'Denver': calc_fine_denver,
    'Seattle': calc_fine_seattle,
    'San Francisco': calc_fine_sf,
    'St. Louis': calc_fine_stlouis,
}

# =============================================================================
# MAIN PROCESSING
# =============================================================================

def process_csv(input_csv):
    """Process a single CSV file and add columns."""
    print(f"\n{'='*60}")
    print(f"Processing: {input_csv}")
    print("="*60)

    df = pd.read_csv(input_csv, low_memory=False)
    print(f"Total rows: {len(df)}")

    # Extract city for all rows
    print("\nExtracting cities from addresses...")
    df['loc_city'] = df.apply(lambda row: extract_city(
        str(row.get('loc_address', '')),
        str(row.get('loc_state', ''))
    ), axis=1)

    city_fill = df['loc_city'].notna().sum()
    print(f"Cities extracted: {city_fill}/{len(df)} ({100*city_fill/len(df):.2f}%)")

    # Initialize fine columns (carbon is calculated separately)
    df['bps_fine_baseline_yr1_usd'] = 0.0
    df['bps_fine_post_odcv_yr1_usd'] = 0.0
    df['bps_fine_avoided_yr1_usd'] = 0.0

    # Process all buildings - exemptions handled per-city below
    all_buildings_mask = df['id_building'].notna()
    print(f"\nTotal buildings: {all_buildings_mask.sum()}")

    # Calculate for each BPS city
    print("\nCalculating fines by city...")
    bps_stats = {}

    # ==========================================================================
    # BPS EXEMPTIONS BY CITY (based on official law research Dec 2025)
    # ==========================================================================
    # NYC LL97: Houses of worship fully exempt; affordable housing & city buildings
    #           have alternative compliance under Article 321 (not standard fines)
    # Denver:   K-12 schools and government buildings have different compliance pathways
    # Cambridge: Only non-residential buildings subject to emission reduction fines
    #           (residential buildings exempt from emission reduction per 2023 amendment)
    # Boston, DC, Seattle, St. Louis: No K-12/govt exemptions - all building types fined
    # ==========================================================================

    # Cities that EXEMPT K-12 and Government buildings from standard BPS fines
    EXEMPT_K12_GOV = ['New York', 'Denver']

    for city_name, calc_func in FINE_CALCULATORS.items():
        # Base mask: buildings in this city
        city_base_mask = df['loc_city'] == city_name

        # Apply exemptions based on city-specific rules
        if city_name in EXEMPT_K12_GOV:
            # NYC & Denver: K-12 schools and government buildings have alternative compliance
            city_mask = city_base_mask & (df['bldg_vertical'] != 'Government') & (df['bldg_vertical'] != 'K-12 School')
        else:
            # Boston, Cambridge, DC, Seattle, St. Louis - include ALL commercial building types
            city_mask = city_base_mask

        city_count = city_mask.sum()

        if city_count > 0:
            results = df.loc[city_mask].apply(calc_func, axis=1, result_type='expand')
            # results: [0]=carbon_reduction, [1]=baseline_fine, [2]=post_odcv_fine
            df.loc[city_mask, 'bps_fine_baseline_yr1_usd'] = results[1]
            df.loc[city_mask, 'bps_fine_post_odcv_yr1_usd'] = results[2]
            df.loc[city_mask, 'bps_fine_avoided_yr1_usd'] = results[1] - results[2]

            total_fine_avoidance = df.loc[city_mask, 'bps_fine_avoided_yr1_usd'].sum()
            buildings_with_fines = (df.loc[city_mask, 'bps_fine_avoided_yr1_usd'] > 0).sum()

            bps_stats[city_name] = {
                'count': city_count,
                'fine_avoidance': total_fine_avoidance,
                'buildings_with_fines': buildings_with_fines,
                'law': BPS_LAWS[city_name]['law_name'],
            }

            print(f"  {city_name} ({BPS_LAWS[city_name]['law_name']}): "
                  f"{city_count} buildings, "
                  f"{buildings_with_fines} with fines, "
                  f"${total_fine_avoidance:,.0f} avoided")

    # Non-BPS cities: no fine avoidance (carbon already calculated separately)
    non_bps_count = (~df['loc_city'].isin(FINE_CALCULATORS.keys())).sum()
    print(f"\n  Non-BPS cities: {non_bps_count} buildings (no fines)")

    # Save updated CSV
    print(f"\nSaving to: {input_csv}")
    df.to_csv(input_csv, index=False)

    # Print summary
    print("\n" + "-"*60)
    print("SUMMARY - FINE AVOIDANCE YEAR 1")
    print("-"*60)

    total_fines = df['bps_fine_avoided_yr1_usd'].sum()

    print(f"Total Buildings Processed: {len(df):,}")
    print(f"Total Fine Avoidance (Year 1): ${total_fines:,.0f}")

    print("\nBy BPS City:")
    for city_name, stats in sorted(bps_stats.items(), key=lambda x: -x[1]['fine_avoidance']):
        print(f"  {city_name} ({stats['law']}): ${stats['fine_avoidance']:,.0f}")

    return df, bps_stats


if __name__ == "__main__":
    print("="*60)
    print("National BPS Carbon Fines Calculator")
    print("="*60)
    print(f"Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    for csv_file in INPUT_CSVS:
        process_csv(csv_file)

    print("\n" + "="*60)
    print(f"Completed: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("="*60)
