"""
Portfolio Organizations List
Generated from portfolio_data.csv

Definition: Organizations appearing in 3+ separate building rows
(per portfolio_identification_methodology.md)

Total: 1037 portfolio organizations
"""

PORTFOLIO_ORGANIZATIONS = [
    "1776 Portfolio Investment, LLC",
    "3D Investments",
    "99 Ranch Market",
    "A. Trenkmann Estate Inc.",
    "A.R.I Investors Inc",
    "ABS Partners Real Estate LLC",
    "ADAM Asset Mgmt",
    "AEW Capital Management",
    "AFIAA Investment Foundation",
    "AMC Entertainment Holdings, Inc. (AMC)",
    "APF Properties",
    "ASB Real Estate",
    "ATCO",
    "Abbott Laboratories",
    "Abner Properties",
    "Abramson Brothers",
    "Academy Of Art University",
    "Acadia Realty Trust",
    "Acc, LLC",
    "Accenture",
    "Accor",
    "Ace Hotels",
    "Acero Schools",
    "Acorn Development",
    "Adams & Company Real Estate",
    "Adobe",
    "Adventist Hospital",
    "Advocate Health",
    "Aegis Living",
    "Aerotek",
    "Aetna Realty",
    "Affinius Capital",
    "Afscme",
    "Ahold Delhaize",
    "Akamai Technologies",
    "Akridge",
    "Albany City Unified School District",
    "Albertsons Companies",
    "Alexandria Real Estate Equities",
    "Alhambra Unified School District",
    "Alice Re Holdings LLC",
    "Alliance For Progress Cs",
    "AllianceBernstein",
    "Allied Partners",
    "Allstate",
    "Altera Corp",
    "Alvord Unified School District",
    "AmTrust Realty Corp",
    "Amazon",
    "American Assets Trust",
    "American Automobile Association",
    "American Broadcasting Company (ABC)",
    "American Century Realty, INC.",
    "American Consumer Credit Counseling, INC.",
    "American National Red Cross",
    "American Realty Advisors",
    "American University",
    "Ameritus",
    "Amtrak",
    "Anaheim Union High School District",
    "Antelope Valley Union High School District",
    "Apollo Global Management",
    "Apple Hospitality REIT",
    "Apple Inc",
    "Applied Materials",
    "Arden Realty, Inc.",
    "Ares Management",
    "Aritzia",
    "Art Center College Of Design",
    "Ascension Health",
    "Ash Management",
    "Ashford Hospitality Trust",
    "Ashley HomeStore",
    "Aspen Meadow Public District",
    "Aspen Valley Prep Academy District",
    "Aspira INC. Of Illinois",
    "At Home",
    "Ateret Torah Center",
    "Atlas Capital Group",
    "Atria Senior Living",
    "Atrius Health",
    "Aurora Capital Associates",
    "Autodesk",
    "Avison Young",
    "Ayres Hotel",
    "B.H. Management Inc.",
    "BJ's Wholesale Club",
    "BMS Realty Services",
    "Bain Capital",
    "Bakersfield City School District",
    "Baldy View Rop",
    "Bank of America",
    "Banyan Street Capital",
    "Barings",
    "Barker Pacific Group",
    "Barnes-Jewish Hospital",
    "Bass Pro Shops",
    "Bay Meadows Station Investors, LLC",
    "Baypoint Preparatory Academy - San Diego District",
    "Beacon Capital Partners",
    "Bellevue Union School District",
    "BentallGreenOak (BGO)",
    "Berik Management",
    "Berklee College Of Music",
    "Bernstein Real Estate",
    "Best Buy",
    "Best Western",
    "Beth Israel Deaconess Medical Center",
    "Betty Shabazz Internl Chrtr Sch",
    "Biomed Realty",
    "Bixby Land Company",
    "BlackRock",
    "Blackstone",
    "Blake Real Estate INC",
    "Block Buildings",
    "Block Real Estate Services, LLC",
    "Blue Woods Management Group, Inc.",
    "Blumenfeld Development Group",
    "Bnos Zion Of Bobov INC (New York)",
    "Bny Mellon",
    "Boeing",
    "Bonafide Estates",
    "Boost Mobile",
    "Boston Center For The Arts",
    "Boston Children's Hospital",
    "Boston College",
    "Boston Medical Center",
    "Boston Properties (BXP)",
    "Boston Public Library",
    "Boston University",
    "Boston-based Tritower Financial Group",
    "Boulevard Investment Group, INC.",
    "Braemar Hotels & Resorts",
    "Brandywine Realty Trust",
    "Brause Realty",
    "Brawner Company, Inc.",
    "Brennan Properties",
    "Brentwood Union Elementary School District",
    "Brickman",
    "Brigham And Women's Hospital",
    "Broadcom INC.",
    "Bronx-Lebanon Hospital Center",
    "Bronzeville Academy Chtr School",
    "Brookdale Senior Living",
    "Brookfield",
    "Buckingham Browne And Nichols School (Cambridge)",
    "Burlington Stores",
    "CBRE Group (CBRE)",
    "CBS Broadcasting (CBS)",
    "CIM Group",
    "CVS Health",
    "Cabrillo Unified School District",
    "Cajon Valley Union School District",
    "California Department of Transportation (Caltrans)",
    "California Education Authority",
    "California Montessori Project - Elk Grove Campus District",
    "California State Teachers' Retirement System (CalSTRS)",
    "California State University",
    "Calvary Chapel",
    "Cammeby's",
    "Cannon Hill Capital Partners",
    "Capistrano Unified School District",
    "Capital One",
    "Cardenas Markets",
    "CareTrust REIT",
    "Carlsbad Unified School District",
    "Carlton Senior Living",
    "Carr Properties",
    "Castro Properties LLC",
    "Catholic Charities",
    "Catholic High School Association (New York)",
    "Cedars-Sinai",
    "Centaur Properties",
    "Central Calif Migrant Head Start Jpa",
    "Central Stickney Sd 110",
    "Central Unified School District",
    "CenturyLink",
    "Cerberus Capital",
    "Cerritos Tc Property Owner Jv LLC",
    "Chaffey Community College District",
    "Chapman University",
    "Charles Dunn Real Estate Services",
    "Charles Schwab",
    "Charter Communications",
    "Chetrit Group",
    "Chicago International Charter School",
    "Chicago Public Schools",
    "Children's Hospital Los Angeles",
    "Children's Mercy Hospital",
    "Children's National Medical Center",
    "Choice Hotels",
    "Chromium LLC",
    "Church Of Scientology",
    "Cinemark Holdings",
    "Circle Realty Group",
    "Cisco Systems",
    "Citigroup",
    "Citizenm",
    "Citizens",
    "City Light",
    "City National Bank",
    "City Of Atlanta",
    "City Of Boston",
    "City Of Cambridge",
    "City Of Chicago",
    "City Of Denver",
    "City Of Inglewood",
    "City Of Los Angeles",
    "City Of New York",
    "City Of Philadelphia",
    "City Of Portland",
    "City Of Sacramento",
    "City Of Seattle",
    "City Of St. Louis",
    "City Office REIT",
    "City University of New York (CUNY)",
    "Cj Segerstrom & Sons",
    "Clarion Partners",
    "Classical Academy High District",
    "Clear Channel Outdoor",
    "Club Quarters",
    "CodeGreen Solutions Inc.",
    "Cogir Senior Living",
    "Cohen Brothers",
    "Collaborative Project Consulting",
    "College Of The Sequoias",
    "Colliers",
    "Colton Joint Unified School District",
    "Columbia College Chicago",
    "Columbia Property Trust",
    "Columbia University",
    "Columbus Properties",
    "Comcast Corporation",
    "CommonWealth Partners",
    "Commonspirit Health",
    "Commonwealth Of Massachusetts",
    "Commonwealth Of Pennsylvania",
    "Community College Of Philadelphia",
    "Community Hospital",
    "Community Montessori District",
    "Condren Realty Mgmt",
    "Confluence Academy",
    "Consolidated Edison (ConEd)",
    "Contra Costa Community College District",
    "Contractors' Warehouse",
    "Convene",
    "Cook County",
    "Cornell University",
    "Cornish College Of The Arts",
    "Corona-Norco Unified School District",
    "Costco",
    "Cousins Properties",
    "Covina Valley Unified School District",
    "Cp Property Owner LLC",
    "Crale Realty",
    "Creative Media & Community Trust",
    "Curtis Investment Group",
    "Cushman & Wakefield",
    "Cutler-Orosi Joint Unified School District",
    "Cypress Elementary (Cypress)",
    "DC Preparatory Academy",
    "DWS Group",
    "Dana-Farber Cancer Institute",
    "Dast Holding CORP",
    "Davies Wallis Foyster (DWF)",
    "Davis Joint Unified School District",
    "Dc Public Library",
    "DePaul University",
    "Decron Properties",
    "Dehesa Elementary School District",
    "Deka Immobilien Investment",
    "Del Mar Union Elementary School District",
    "Delano Joint Union High School District",
    "Delano Union Elementary School District",
    "Deloitte",
    "Denver Public Schools",
    "Department Of Citywide Administrative Services",
    "Des Moines Public Schools (Chicago)",
    "Desert Sands Unified School District",
    "Dezer Properties",
    "Digital Realty",
    "District Of Columbia",
    "District Of Columbia International School",
    "District Of Columbia Public Schools",
    "DivcoWest",
    "Dollar Tree",
    "Donohoe",
    "Douglas Development",
    "Douglas Elliman",
    "Douglas Emmett",
    "Downtown Properties",
    "Drexel University",
    "Drollinger Properties",
    "Drury Development Corporation",
    "Drury Hotels",
    "Dry Creek Joint Elementary School District",
    "Dst Realty INC",
    "Dublin Unified School District",
    "ELV Associates Inc.",
    "EPR Properties",
    "EQ Office",
    "Eagle Point",
    "Eastgate",
    "Eastside Union Elementary School District",
    "Ebay",
    "Edison Properties",
    "Edward J. Minskoff Equities",
    "El Dorado Union High School District",
    "El Rancho Unified School District",
    "Elijah Equities",
    "Elk Grove Unified School District",
    "Ellman Realty Advisors",
    "Elo Realty",
    "Embarcadero Capital Partners",
    "Emblem Health",
    "Emerson College",
    "Emmanuel College",
    "Emory University",
    "Empire Leasing, Inc.",
    "Empire Park Realty Investments",
    "Empire State Realty Trust",
    "Enchante Accessories",
    "Eq Management LLC",
    "Equity One LLC",
    "Eretz Group",
    "Ericsson, INC.",
    "Eskaton",
    "Esplanade 99 LLC",
    "Eugenio Maria De Hostos Cs",
    "Extell Development",
    "Extended Stay America",
    "FCA Partners",
    "Fairfield-Suisun Unified School District",
    "Falcon Properties",
    "Fannie Mae",
    "Farmers Insurance",
    "Fashion Options",
    "Fatollah Hematian",
    "Federal Realty",
    "Federal Reserve Bank",
    "Feil Organization",
    "Fenway Capital Advisors, LLC",
    "Fidelity Investments",
    "Fig Garden Financial",
    "First Pioneer Properties",
    "Fisher Brothers Mgmt",
    "Flagstar Bank",
    "Floor & Decor",
    "Folsom Cordova Unified School District",
    "Fontana Unified School District",
    "Fordham University",
    "Fort Point Channel Investors LLC",
    "Fortinet",
    "Fortress Investment Group",
    "Fountain Valley Elementary School District",
    "Four Seasons",
    "Fox Associates LP",
    "Franklin Elementary School District",
    "Franklin Resources",
    "Franklin Street Properties",
    "Fred Hutchinson Cancer Center (Fred Hutch)",
    "Fresno County",
    "Fresno Unified School District",
    "Friedman Properties Ltd.",
    "Friendship Public Charter School (Washington)",
    "G.H. Palmer Associates",
    "GFP Real Estate",
    "Gap INC.",
    "Garden Grove Unified School District",
    "Gateway International District",
    "Gaw Capital Partners",
    "Gelb Enterprises",
    "Gelson's",
    "Genentech",
    "General Services Administration (GSA)",
    "George Comfort & Sons",
    "George Washington University",
    "Georgetown University",
    "Gilead Sciences",
    "Glendale Unified School District",
    "Global Holdings",
    "Goldman Sachs",
    "Goodwill",
    "Google",
    "Gordon Property Group LLC",
    "Gorjian Real Estate Group",
    "Grainger Industrial Supply",
    "Granite Properties",
    "Greenfield Union School District",
    "Greenlaw Partners",
    "Greystone",
    "Grocery Outlet Bargain Market",
    "Grosvenor",
    "Group Real Estate Development LLC",
    "Grunberg Realty",
    "H&M",
    "HCA Healthcare",
    "HCRE",
    "Habitat For Humanity Restore",
    "Hackman Capital Partners",
    "Hallmark Cards Inc",
    "Handler Real Estate Services",
    "Hankey Investment Company LP",
    "Harbor Group",
    "Harborview Medical Center",
    "Harvard University",
    "Harvest Properties",
    "Hauser & Wirth",
    "Hd Development Of Maryland, INC.",
    "Health Sciences High District",
    "Health Sciences Middle District",
    "Healthcare Realty",
    "Healthpeak Properties",
    "Hearst",
    "Heitman",
    "Heller Properties",
    "Hersha Hospitality Trust",
    "Heskel's Asset Mgmt",
    "Hesperia Unified School District",
    "Hickman Mills C-1",
    "High Tech Elementary Mesa District",
    "Highwoods Properties",
    "Hilson Management Corp.",
    "Hilton",
    "Himmel + Meringoff Properties LLC",
    "Hines",
    "Hive Property Owner LLC",
    "Hobby Lobby",
    "Holy Family University",
    "Homes For The Homeless Institute",
    "Horizon Science Acad-Mckinley Pk",
    "Hospital For Special Surgery",
    "Host Hotels & Resorts",
    "Hotel 21",
    "Howard University",
    "Hudson Pacific Properties",
    "Human Resources Administration",
    "Hyatt",
    "IKEA",
    "IQHQ",
    "Ids Real Estate Group",
    "Illinois Institute Of Technology",
    "Industrious",
    "Inspire Brands",
    "Intel",
    "InterContinental Hotels Group (IHG)",
    "Intercontinental Real Estate",
    "International Bank For Reconstruction & Development",
    "Invesco",
    "Ivy Park",
    "J Street Property Services LLC",
    "J.W. Mays",
    "JBG Smith Properties",
    "JEMB Realty Corporation (JEMB)",
    "JPMorgan Chase (JPM)",
    "Jack Resnick & Sons",
    "Jamaica Hospital",
    "James Campbell Company, LLC",
    "Jamestown L.P.",
    "Jamison Services",
    "Janus Property",
    "Jay Suites",
    "Jcpenney",
    "Jenel Management",
    "Jerome's Furniture & Mattress Store",
    "Jewish Board of Family and Children's Services",
    "Jewish Community Center",
    "Jewish Home And Hospital",
    "John Hancock",
    "Johns Hopkins University",
    "Jones Lang LaSalle (JLL)",
    "Jordache Enterprises",
    "Joseph P. Day",
    "Journey District",
    "Jujamcyn Theaters LLC",
    "Junius Development",
    "Jurupa Unified School District",
    "Justin Management",
    "KBS Realty",
    "KCG Development",
    "KIPP Schools",
    "KKR",
    "KPB Immigration Law Firm",
    "KPMG",
    "Kairos Public School Vacaville Academy District",
    "Kaiser Permanente",
    "Kansas City Public Schools",
    "Kaufman Organization",
    "Keiller Leadership Academy District",
    "Kennedy Wilson",
    "Kerman Unified School District",
    "Kern County",
    "Kern High School District",
    "Kew Mgmt",
    "Kf Braun",
    "Kg Investment Properties",
    "Kiamie Industries",
    "Kidinnu Academy District",
    "Kilroy Realty",
    "Kimberly Holdings, LLC",
    "Kimco Realty Corporation",
    "King County",
    "King Terminal LLC Mass LLC",
    "King-Chavez Academy Of Excellence District",
    "Kings Canyon Joint Unified School District",
    "Kings County",
    "Knotel",
    "Koeppel Rosen",
    "Kohl's",
    "Korea Investment Corporation",
    "Kroger",
    "L&L Holding",
    "LBA Realty",
    "LUMA Hotel",
    "LVMH Moet Hennessy Louis Vuitton (LVMH)",
    "La Caisse",
    "La Salle University",
    "Lake Realty Management LLC",
    "Lam Research",
    "Latin School Of Chicago",
    "Lawrence Group",
    "Leadership Military Academy - Indio District",
    "Lebeau Realty & Associates",
    "Lee & Associates",
    "Lefrak",
    "Legend Real Estate Management",
    "Lesley University",
    "Lincoln Property Company",
    "Living Spaces",
    "Lodi Unified School District",
    "Loews Hotels",
    "Loma Linda University",
    "Long Beach Unified School District",
    "Longwood Management",
    "Los Angeles County",
    "Los Angeles Unified School District",
    "Los Angeles World Airports",
    "Los Banos Unified School District",
    "Lowe's",
    "Lsl Advisors",
    "Lucky",
    "MCR Hotels",
    "MD Carlisle",
    "MGR Holdings, LLC",
    "MHF",
    "MJ Orbach",
    "MRP Realty",
    "MacTaggart Family",
    "Macerich",
    "Macklowe Management",
    "Macy's",
    "Madera Unified School District",
    "Magnolia Science Academy San Diego District",
    "Maimonides Medical Center",
    "Manhattan College",
    "Manova Partners Inc.",
    "Manulife",
    "Marc Realty",
    "Marin County",
    "Marriott",
    "Marx Realty",
    "Marysville Joint Unified School District",
    "Massachusetts Institute Of Technology",
    "Matern Law Group, PC",
    "Mather",
    "McDonald's",
    "McKinsey & Company",
    "McKinstry",
    "Meadow Partners",
    "Medtronic, INC.",
    "Mehra Properties Inc.",
    "Memorial Sloan Kettering Cancer Center",
    "MemorialCare Health System",
    "Menifee Union School District",
    "Menlo Equities",
    "Merrill Gardens",
    "MetLife",
    "Meta",
    "Meyer Equities",
    "Michaels",
    "Microsoft",
    "Miracosta College",
    "Mitsui Fudosan America",
    "Mmc Corporation",
    "Modesto City Schools",
    "Moinian Group",
    "Mojave River Academy",
    "Monarchs Sub, LLC",
    "Montague-Lee Limited Partnership",
    "Montefiore Medical Center",
    "Moreno Valley Unified School District",
    "Morgan Stanley",
    "Motel 6",
    "Mount Sinai Health System",
    "Mountain View Elementary School District",
    "Mourier Land Investment Corporation",
    "Multi-Employer Property Trust (MEPT)",
    "Multnomah County",
    "Munich Re",
    "Museum Of Fine Arts",
    "NAI Global",
    "NVIDIA",
    "Napa County",
    "National Collegiate Preparatory Pchs",
    "National Community Reinvestment Coalition",
    "National University",
    "Neiman Marcus",
    "NetApp",
    "Netflix",
    "New England Conservatory Of Music",
    "New Seasons Market",
    "New York City Geographic District",
    "New York Law School",
    "New York Life Insurance Company",
    "New York Public Library",
    "New York University (NYU)",
    "New York-Presbyterian Hospital",
    "Newmark",
    "Newport Healthcare Center, LLC",
    "Nextplay Consulting LLC",
    "Nicotra Group",
    "Nike",
    "Nokia",
    "Nordstrom",
    "Norges Bank Investment Management",
    "North American Properties",
    "North Side Community School",
    "Northbay Health",
    "Northeastern Illinois University",
    "Northeastern University",
    "Northern Star LLC",
    "Northern Trust",
    "Northwestern Memorial Hospital",
    "Northwestern Mutual",
    "Northwestern University",
    "Northwood Investors",
    "Oakmont Senior Living",
    "Ocean View",
    "Ocean West Management Services",
    "Oceanside Unified School District",
    "Office Depot/Officemax",
    "Office Properties Income Trust",
    "Okada & Company",
    "Olmstead Properties",
    "Omega Healthcare Investors",
    "Omni Hotel",
    "Onni Group",
    "Options For Youth-Acton District",
    "Oracle",
    "Orange County",
    "Orchard Commercial, INC.",
    "Oxford Preparatory Academy",
    "Oxford Properties Group",
    "Oyster-Adams Bilingual School (Adams)",
    "PM Realty Group",
    "PNC Bank",
    "PRD Realty",
    "PSP Investments",
    "Pace University",
    "Pacific Union Elementary School District",
    "Pali Management Group",
    "Parallel Capital Partners",
    "Paramount Group",
    "Paramount Studios",
    "Park Hill R-5 School District",
    "Park Hotels & Resorts",
    "Partnership Healthplan Of California",
    "Patterson Joint Unified School District",
    "Pembroke",
    "Pendry Hotels",
    "Pendulum Property Partners",
    "Penumbra",
    "Petco",
    "Pete's Fresh Market",
    "Philadelphia County",
    "Philadelphia University",
    "Physicians Medical Center",
    "Piedmont Office Realty Trust",
    "Pih Health",
    "Pittsburg Unified School District",
    "Pixar",
    "Placer County",
    "Planned Parenthood",
    "Pleasanton Unified School District",
    "Plumas Lake Elementary (Olivehurst)",
    "Point West Office Investors, LLC",
    "Polinger Co. - 2401 Pennsylvania Avenue Residences",
    "Pontegadea",
    "Port Authority Of Kcmo",
    "Port Of Seattle",
    "Portland Community College",
    "Portland State University",
    "Potomac Investment Properties",
    "Pratt Institute",
    "Prime Healthcare Services",
    "Princeton International Properties",
    "Principal Real Estate Investors",
    "Progressive Insurance",
    "Property Group Partners",
    "Prospect Health System",
    "Providence Health",
    "Publix",
    "PwC",
    "Pyrus Management LLC",
    "Quadrangle Management Company",
    "Qualcomm",
    "Quartermaster Plaza 1777 LLC",
    "Quest Diagnostics",
    "RFR Realty",
    "RLJ Lodging Trust",
    "RNM Properties",
    "RXR Realty",
    "Raber Enterprises",
    "Rainier Valley Leadership Academy",
    "Raintree Realty II, LLC",
    "Raley's",
    "Ranken Technical College",
    "Realty Income Corporation",
    "Rebel Hospitality",
    "Redcar Properties LTD",
    "Regal Entertainment",
    "Regus",
    "Related Companies",
    "Renaissance Properties",
    "Republic Properties Corporation",
    "Resolution Real Estate",
    "Restaurant Depot",
    "Restoration Hardware",
    "Rexford Industrial",
    "Rialto Unified School District",
    "Rising Realty Partners",
    "Rite Aid",
    "RiverRock Real Estate Group",
    "Riverdale Country School (New York)",
    "Riverside Community College District",
    "Riverside County",
    "Riverside Unified School District",
    "Robertson Properties Group",
    "Rocco Tomassetti",
    "Rockefeller Group",
    "Rockhill Management, L.L.C.",
    "Rockhurst University",
    "Rockpoint Group",
    "Rockrose Development",
    "Rockwood Capital",
    "Roman Catholic Archdiocese Of Washington",
    "Roman Catholic Church",
    "Ronald McDonald House Charities",
    "Room & Board",
    "Roosevelt Lee",
    "Rosen Equities",
    "Roseville Joint Union High School District",
    "Ross Stores",
    "Rubicon Point Partners",
    "Rudin Management Co. Inc.",
    "Rush University Medical Center (RUMC)",
    "S.C. Herman & Associates, Inc.",
    "SEPHORA",
    "SL Green",
    "SSM Health",
    "Sacramento City Unified School District",
    "Sacramento County",
    "Saddleback Valley Unified School District",
    "Safety Training Seminars",
    "Sage Realty",
    "Saks Fifth Avenue",
    "Salesforce",
    "Samco Properties",
    "Samson",
    "San Antonio Regional Hospital",
    "San Bernardino City Unified School District",
    "San Bernardino Community College District",
    "San Bernardino County",
    "San Diego Gas & Electric",
    "San Diego Unified School District",
    "San Jacinto Unified School District",
    "San Jose City College",
    "San Jose Unified School District",
    "San Juan Unified School District",
    "San Lorenzo Unified School District",
    "San Marcos Unified School District",
    "San Mateo Union High School District",
    "San Pasqual Union Elementary School District",
    "Sanger Unified School District",
    "Santa Clara County",
    "Santa Clara Unified School District",
    "Santa Maria Joint Union High School District",
    "Santa Monica College",
    "Santa Monica-Malibu Unified School District",
    "Santa Rosa City Schools",
    "Santee School District",
    "Sapir Organization",
    "Savanna Real Estate",
    "Savannah College Of Art And Design",
    "Savitt Partners",
    "Schnucks",
    "School District of Philadelphia",
    "School Of The Art Institute Of Chicago",
    "Schoolsfirst Federal Credit Union",
    "Schur Management Company",
    "Scientific Games",
    "Scripps Health",
    "Sears",
    "Seattle Cancer Care Alliance",
    "Seattle Central College",
    "Seattle Children's Hospital",
    "Seattle Public Schools",
    "Senior Suites",
    "Service Properties Trust",
    "Sharp HealthCare",
    "ShopRite",
    "Shorenstein Properties",
    "Shriners Hospitals For Children",
    "Shubert Theatre",
    "Shulsky Properties",
    "Sierra Pacific Properties",
    "Silk And Halpern",
    "Silver Cloud Inn",
    "Silvercup Studios",
    "Silvergate Residential Care",
    "Silverstein Properties",
    "Simmons University",
    "Simon Property Group",
    "Sinvin",
    "Sioni Group",
    "Smart & Final",
    "Snowflake",
    "Sobrato Organization",
    "Social Security Administration",
    "Sol Vista",
    "Solil Management",
    "Soloviev Group",
    "Sonesta International Hotels",
    "Sony",
    "South Seattle College",
    "Southeastern Pennsylvania Transportation Authority (SEPTA)",
    "Southern California Edison",
    "Southern Company",
    "Sovereign Partners",
    "Spaces",
    "Spar Knitwear CORP",
    "Spear Street Capital",
    "Spectrum Properties Group Inc.",
    "Spirit Halloween",
    "Sprouts Farmers Market",
    "St Jude Medical Center",
    "St. John's Place Family Center",
    "St. John's University",
    "St. Louis Public Schools",
    "St. Luke's Hospital",
    "Stahl Organization",
    "Stanford University",
    "Starpointe Management LLC",
    "Stars REI",
    "Starwood Capital",
    "State Farm",
    "State Of New York",
    "State Of Oregon",
    "State Of Washington",
    "State Street",
    "State of California",
    "Staten Island University Hospital",
    "Stater Bros. Markets",
    "Stawski Partners",
    "Steel Equities",
    "Steelwave",
    "Steinberg",
    "Stellar Management",
    "Stephens Institute",
    "Sterling Bay",
    "Stockton Unified School District",
    "Stoladi Property Group, Inc.",
    "Stonebridge",
    "Stony Point East LP",
    "Stout & Teague Companies",
    "Stream Realty Partners",
    "Suffolk University",
    "Sulphur Springs Union School District",
    "Summit Hotel Properties",
    "Summit Public Schools",
    "Sundale Union Elementary School District",
    "Sunrise Senior Living",
    "Sunset Development Company",
    "Sutter Health",
    "Swedish Medical Center",
    "Swift Real Estate Partners",
    "Swig Company",
    "Sycamore Academy Of Science And Cultural Arts Chino Vly District",
    "Symantec Corporation",
    "Synergy Investments",
    "T-Mobile",
    "T. Rowe Price",
    "TA Realty",
    "TD Bank",
    "TF Cornerstone Inc.",
    "TIAA",
    "TJX Companies",
    "TMG Partners",
    "TMT Development",
    "Taconic Partners",
    "Target",
    "Temecula Valley Unified School District",
    "Temple University",
    "Terreno Realty",
    "Tesla",
    "The 58-64 40 St. Corp., Inc",
    "The Arch Community School",
    "The Ashtin Group, Inc.",
    "The Biome",
    "The Davis Companies",
    "The Doyle Collection",
    "The Durst Organization",
    "The Education Corps District",
    "The Eric Ryan Corporation",
    "The Evergreen Company",
    "The Home Depot",
    "The Irvine Company",
    "The John Buck Company",
    "The Lenkin Company",
    "The Meridian Group",
    "The Muller Company",
    "The New School",
    "The Pacifica Company, LP.",
    "The Philadelphia Cs For Arts And Sciences At Hr Edmunds",
    "The RMR Group",
    "The Salvation Army",
    "The Soulard School",
    "The Tower Companies",
    "Thomas Jefferson University",
    "Thor Equities",
    "Tiarna Real Estate Services",
    "Time Equities",
    "Tishman Speyer",
    "Tpp-Lpw Som Property LLC",
    "Transwestern",
    "Travis Unified School District",
    "Tri City Acquisitions",
    "Triad Management Systems INC.",
    "Triangle Assets",
    "Trigon Equities",
    "Trinity Church",
    "Trinity Real Estate",
    "Triumph Hotels",
    "Truist",
    "Truman Medical Center",
    "Trump Organization",
    "Tufts University",
    "Turner Broadcasting",
    "Twin Rivers Unified School District",
    "Two Trees Management",
    "UBS",
    "UMB Bank",
    "UNIZO Holdings",
    "US Bank",
    "US. Federal Government",
    "USAA Real Estate",
    "Uci Health",
    "Unibail-Rodamco-Westfield",
    "Unico Properties",
    "Union Investment Real Estate GmbH",
    "Unire Real Estate Group",
    "United Cerebral Palsy Of New York City",
    "United Talmudical Academy (New York)",
    "United Way",
    "Unity Health Care",
    "University Of Chicago",
    "University Of Denver",
    "University Of Pennsylvania",
    "University Of Portland",
    "University Of San Francisco",
    "University Of Southern California",
    "University Of The District Of Columbia",
    "University of California",
    "University of Illinois Foundation",
    "University of Washington (UW)",
    "Urban Innovations",
    "Urban Outfitters",
    "Urban Renaissance Group",
    "VMware",
    "Vacaville Unified School District",
    "Valencia College",
    "Vallarta Supermarkets",
    "Vanbarton Group",
    "Various Tenants",
    "Ventas",
    "Vert Energy Group",
    "Virginia Mason",
    "Visa",
    "Visalia Unified School District",
    "Vision Quest & Career Pathway District",
    "Voices College-Bound Language Acad At Mt. Pleasant District",
    "Vornado Realty Trust",
    "WC Smith",
    "WFG National Title Insurance Company",
    "WMC Associates",
    "Walgreens",
    "Walmart",
    "Walt Disney Imagineering",
    "Walter & Samuels",
    "Warner Bros Discovery",
    "Washington Hospital Healthcare",
    "Washington Metropolitan Area Transit Authority",
    "Washington Unified School District",
    "Washington University in St. Louis",
    "Waterman Properties",
    "Waverly Management",
    "Wells Fargo",
    "Welltower",
    "Wentworth Institute Of Technology",
    "Wespac Management Group, INC",
    "West Coast University",
    "West Contra Costa Unified School District",
    "Western University Of Health Sciences",
    "Westlake Park Place Inc.",
    "Westminster",
    "Westside Union Elementary School District",
    "Wework",
    "Wharton Properties",
    "Wildflower Open Classroom District",
    "Willco Companies",
    "William S. Hart Union High School District",
    "Williams Equities",
    "Winco Foods",
    "Windsor Mgmt",
    "Windsor Unified School District",
    "Winoker Realty",
    "Winter Organization",
    "Workday",
    "Worthe Real Estate",
    "Wyndham",
    "YOTEL",
    "Yellowstone Real Estate",
    "Yeshiva University",
    "Young Men's Christian Association (YMCA)",
    "Yuba City Unified School District",
    "Zeller",
    "Zuckerman Gravely Management",
]

# Dict with row counts for reference
PORTFOLIO_ORG_ROW_COUNTS = {
    "1776 Portfolio Investment, LLC": 5,
    "3D Investments": 6,
    "99 Ranch Market": 3,
    "A. Trenkmann Estate Inc.": 4,
    "A.R.I Investors Inc": 3,
    "ABS Partners Real Estate LLC": 27,
    "ADAM Asset Mgmt": 4,
    "AEW Capital Management": 6,
    "AFIAA Investment Foundation": 5,
    "AMC Entertainment Holdings, Inc. (AMC)": 17,
    "APF Properties": 6,
    "ASB Real Estate": 9,
    "ATCO": 6,
    "Abbott Laboratories": 6,
    "Abner Properties": 6,
    "Abramson Brothers": 11,
    "Academy Of Art University": 16,
    "Acadia Realty Trust": 14,
    "Acc, LLC": 3,
    "Accenture": 4,
    "Accor": 8,
    "Ace Hotels": 7,
    "Acero Schools": 6,
    "Acorn Development": 3,
    "Adams & Company Real Estate": 26,
    "Adobe": 10,
    "Adventist Hospital": 31,
    "Advocate Health": 3,
    "Aegis Living": 7,
    "Aerotek": 3,
    "Aetna Realty": 3,
    "Affinius Capital": 5,
    "Afscme": 6,
    "Ahold Delhaize": 30,
    "Akamai Technologies": 3,
    "Akridge": 16,
    "Albany City Unified School District": 3,
    "Albertsons Companies": 199,
    "Alexandria Real Estate Equities": 39,
    "Alhambra Unified School District": 14,
    "Alice Re Holdings LLC": 3,
    "Alliance For Progress Cs": 3,
    "AllianceBernstein": 3,
    "Allied Partners": 5,
    "Allstate": 3,
    "Altera Corp": 3,
    "Alvord Unified School District": 6,
    "AmTrust Realty Corp": 6,
    "Amazon": 44,
    "American Assets Trust": 6,
    "American Automobile Association": 5,
    "American Broadcasting Company (ABC)": 4,
    "American Century Realty, INC.": 4,
    "American Consumer Credit Counseling, INC.": 5,
    "American National Red Cross": 7,
    "American Realty Advisors": 14,
    "American University": 7,
    "Ameritus": 4,
    "Amtrak": 5,
    "Anaheim Union High School District": 4,
    "Antelope Valley Union High School District": 6,
    "Apollo Global Management": 15,
    "Apple Hospitality REIT": 17,
    "Apple Inc": 21,
    "Applied Materials": 9,
    "Arden Realty, Inc.": 13,
    "Ares Management": 4,
    "Aritzia": 3,
    "Art Center College Of Design": 3,
    "Ascension Health": 6,
    "Ash Management": 3,
    "Ashford Hospitality Trust": 17,
    "Ashley HomeStore": 3,
    "Aspen Meadow Public District": 4,
    "Aspen Valley Prep Academy District": 4,
    "Aspira INC. Of Illinois": 3,
    "At Home": 3,
    "Ateret Torah Center": 4,
    "Atlas Capital Group": 3,
    "Atria Senior Living": 7,
    "Atrius Health": 3,
    "Aurora Capital Associates": 7,
    "Autodesk": 3,
    "Avison Young": 45,
    "Ayres Hotel": 19,
    "B.H. Management Inc.": 3,
    "BJ's Wholesale Club": 9,
    "BMS Realty Services": 3,
    "Bain Capital": 3,
    "Bakersfield City School District": 24,
    "Baldy View Rop": 5,
    "Bank of America": 20,
    "Banyan Street Capital": 5,
    "Barings": 4,
    "Barker Pacific Group": 5,
    "Barnes-Jewish Hospital": 4,
    "Bass Pro Shops": 6,
    "Bay Meadows Station Investors, LLC": 4,
    "Baypoint Preparatory Academy - San Diego District": 3,
    "Beacon Capital Partners": 34,
    "Bellevue Union School District": 3,
    "BentallGreenOak (BGO)": 11,
    "Berik Management": 3,
    "Berklee College Of Music": 10,
    "Bernstein Real Estate": 11,
    "Best Buy": 23,
    "Best Western": 38,
    "Beth Israel Deaconess Medical Center": 11,
    "Betty Shabazz Internl Chrtr Sch": 7,
    "Biomed Realty": 19,
    "Bixby Land Company": 3,
    "BlackRock": 3,
    "Blackstone": 38,
    "Blake Real Estate INC": 9,
    "Block Buildings": 3,
    "Block Real Estate Services, LLC": 3,
    "Blue Woods Management Group, Inc.": 5,
    "Blumenfeld Development Group": 3,
    "Bnos Zion Of Bobov INC (New York)": 4,
    "Bny Mellon": 3,
    "Boeing": 5,
    "Bonafide Estates": 5,
    "Boost Mobile": 3,
    "Boston Center For The Arts": 3,
    "Boston Children's Hospital": 4,
    "Boston College": 22,
    "Boston Medical Center": 3,
    "Boston Properties (BXP)": 109,
    "Boston Public Library": 5,
    "Boston University": 40,
    "Boston-based Tritower Financial Group": 3,
    "Boulevard Investment Group, INC.": 4,
    "Braemar Hotels & Resorts": 8,
    "Brandywine Realty Trust": 15,
    "Brause Realty": 8,
    "Brawner Company, Inc.": 3,
    "Brennan Properties": 3,
    "Brentwood Union Elementary School District": 10,
    "Brickman": 6,
    "Brigham And Women's Hospital": 6,
    "Broadcom INC.": 6,
    "Bronx-Lebanon Hospital Center": 6,
    "Bronzeville Academy Chtr School": 6,
    "Brookdale Senior Living": 35,
    "Brookfield": 95,
    "Buckingham Browne And Nichols School (Cambridge)": 3,
    "Burlington Stores": 5,
    "CBRE Group (CBRE)": 296,
    "CBS Broadcasting (CBS)": 6,
    "CIM Group": 20,
    "CVS Health": 29,
    "Cabrillo Unified School District": 3,
    "Cajon Valley Union School District": 4,
    "California Department of Transportation (Caltrans)": 3,
    "California Education Authority": 8,
    "California Montessori Project - Elk Grove Campus District": 3,
    "California State Teachers' Retirement System (CalSTRS)": 5,
    "California State University": 22,
    "Calvary Chapel": 3,
    "Cammeby's": 5,
    "Cannon Hill Capital Partners": 16,
    "Capistrano Unified School District": 25,
    "Capital One": 7,
    "Cardenas Markets": 3,
    "CareTrust REIT": 3,
    "Carlsbad Unified School District": 3,
    "Carlton Senior Living": 9,
    "Carr Properties": 10,
    "Castro Properties LLC": 4,
    "Catholic Charities": 5,
    "Catholic High School Association (New York)": 3,
    "Cedars-Sinai": 4,
    "Centaur Properties": 4,
    "Central Calif Migrant Head Start Jpa": 3,
    "Central Stickney Sd 110": 3,
    "Central Unified School District": 13,
    "CenturyLink": 3,
    "Cerberus Capital": 39,
    "Cerritos Tc Property Owner Jv LLC": 3,
    "Chaffey Community College District": 18,
    "Chapman University": 6,
    "Charles Dunn Real Estate Services": 13,
    "Charles Schwab": 4,
    "Charter Communications": 3,
    "Chetrit Group": 10,
    "Chicago International Charter School": 6,
    "Chicago Public Schools": 214,
    "Children's Hospital Los Angeles": 8,
    "Children's Mercy Hospital": 3,
    "Children's National Medical Center": 3,
    "Choice Hotels": 45,
    "Chromium LLC": 3,
    "Church Of Scientology": 4,
    "Cinemark Holdings": 28,
    "Circle Realty Group": 3,
    "Cisco Systems": 5,
    "Citigroup": 8,
    "Citizenm": 7,
    "Citizens": 3,
    "City Light": 3,
    "City National Bank": 4,
    "City Of Atlanta": 7,
    "City Of Boston": 31,
    "City Of Cambridge": 14,
    "City Of Chicago": 22,
    "City Of Denver": 26,
    "City Of Inglewood": 4,
    "City Of Los Angeles": 29,
    "City Of New York": 184,
    "City Of Philadelphia": 21,
    "City Of Portland": 4,
    "City Of Sacramento": 5,
    "City Of Seattle": 12,
    "City Of St. Louis": 4,
    "City Office REIT": 5,
    "City University of New York (CUNY)": 26,
    "Cj Segerstrom & Sons": 3,
    "Clarion Partners": 6,
    "Classical Academy High District": 5,
    "Clear Channel Outdoor": 3,
    "Club Quarters": 9,
    "CodeGreen Solutions Inc.": 8,
    "Cogir Senior Living": 13,
    "Cohen Brothers": 9,
    "Collaborative Project Consulting": 3,
    "College Of The Sequoias": 3,
    "Colliers": 67,
    "Colton Joint Unified School District": 21,
    "Columbia College Chicago": 12,
    "Columbia Property Trust": 15,
    "Columbia University": 22,
    "Columbus Properties": 3,
    "Comcast Corporation": 5,
    "CommonWealth Partners": 11,
    "Commonspirit Health": 5,
    "Commonwealth Of Massachusetts": 13,
    "Commonwealth Of Pennsylvania": 5,
    "Community College Of Philadelphia": 3,
    "Community Hospital": 6,
    "Community Montessori District": 7,
    "Condren Realty Mgmt": 3,
    "Confluence Academy": 4,
    "Consolidated Edison (ConEd)": 7,
    "Contra Costa Community College District": 5,
    "Contractors' Warehouse": 3,
    "Convene": 3,
    "Cook County": 7,
    "Cornell University": 3,
    "Cornish College Of The Arts": 4,
    "Corona-Norco Unified School District": 38,
    "Costco": 146,
    "Cousins Properties": 16,
    "Covina Valley Unified School District": 7,
    "Cp Property Owner LLC": 4,
    "Crale Realty": 7,
    "Creative Media & Community Trust": 6,
    "Curtis Investment Group": 3,
    "Cushman & Wakefield": 265,
    "Cutler-Orosi Joint Unified School District": 4,
    "Cypress Elementary (Cypress)": 3,
    "DC Preparatory Academy": 3,
    "DWS Group": 22,
    "Dana-Farber Cancer Institute": 3,
    "Dast Holding CORP": 3,
    "Davies Wallis Foyster (DWF)": 9,
    "Davis Joint Unified School District": 9,
    "Dc Public Library": 5,
    "DePaul University": 35,
    "Decron Properties": 3,
    "Dehesa Elementary School District": 6,
    "Deka Immobilien Investment": 10,
    "Del Mar Union Elementary School District": 4,
    "Delano Joint Union High School District": 4,
    "Delano Union Elementary School District": 4,
    "Deloitte": 4,
    "Denver Public Schools": 3,
    "Department Of Citywide Administrative Services": 12,
    "Des Moines Public Schools (Chicago)": 3,
    "Desert Sands Unified School District": 31,
    "Dezer Properties": 11,
    "Digital Realty": 3,
    "District Of Columbia": 79,
    "District Of Columbia International School": 6,
    "District Of Columbia Public Schools": 187,
    "DivcoWest": 12,
    "Dollar Tree": 8,
    "Donohoe": 7,
    "Douglas Development": 31,
    "Douglas Elliman": 5,
    "Douglas Emmett": 103,
    "Downtown Properties": 3,
    "Drexel University": 19,
    "Drollinger Properties": 4,
    "Drury Development Corporation": 4,
    "Drury Hotels": 4,
    "Dry Creek Joint Elementary School District": 4,
    "Dst Realty INC": 4,
    "Dublin Unified School District": 9,
    "ELV Associates Inc.": 3,
    "EPR Properties": 7,
    "EQ Office": 7,
    "Eagle Point": 3,
    "Eastgate": 11,
    "Eastside Union Elementary School District": 6,
    "Ebay": 6,
    "Edison Properties": 3,
    "Edward J. Minskoff Equities": 5,
    "El Dorado Union High School District": 4,
    "El Rancho Unified School District": 4,
    "Elijah Equities": 3,
    "Elk Grove Unified School District": 19,
    "Ellman Realty Advisors": 5,
    "Elo Realty": 10,
    "Embarcadero Capital Partners": 9,
    "Emblem Health": 9,
    "Emerson College": 7,
    "Emmanuel College": 7,
    "Emory University": 43,
    "Empire Leasing, Inc.": 8,
    "Empire Park Realty Investments": 3,
    "Empire State Realty Trust": 25,
    "Enchante Accessories": 3,
    "Eq Management LLC": 5,
    "Equity One LLC": 4,
    "Eretz Group": 4,
    "Ericsson, INC.": 3,
    "Eskaton": 3,
    "Esplanade 99 LLC": 3,
    "Eugenio Maria De Hostos Cs": 3,
    "Extell Development": 11,
    "Extended Stay America": 55,
    "FCA Partners": 5,
    "Fairfield-Suisun Unified School District": 6,
    "Falcon Properties": 5,
    "Fannie Mae": 4,
    "Farmers Insurance": 4,
    "Fashion Options": 4,
    "Fatollah Hematian": 4,
    "Federal Realty": 7,
    "Federal Reserve Bank": 4,
    "Feil Organization": 20,
    "Fenway Capital Advisors, LLC": 3,
    "Fidelity Investments": 6,
    "Fig Garden Financial": 3,
    "First Pioneer Properties": 7,
    "Fisher Brothers Mgmt": 5,
    "Flagstar Bank": 3,
    "Floor & Decor": 14,
    "Folsom Cordova Unified School District": 10,
    "Fontana Unified School District": 20,
    "Fordham University": 3,
    "Fort Point Channel Investors LLC": 6,
    "Fortinet": 4,
    "Fortress Investment Group": 11,
    "Fountain Valley Elementary School District": 4,
    "Four Seasons": 10,
    "Fox Associates LP": 3,
    "Franklin Elementary School District": 4,
    "Franklin Resources": 5,
    "Franklin Street Properties": 6,
    "Fred Hutchinson Cancer Center (Fred Hutch)": 4,
    "Fresno County": 4,
    "Fresno Unified School District": 54,
    "Friedman Properties Ltd.": 9,
    "Friendship Public Charter School (Washington)": 8,
    "G.H. Palmer Associates": 11,
    "GFP Real Estate": 46,
    "Gap INC.": 7,
    "Garden Grove Unified School District": 9,
    "Gateway International District": 3,
    "Gaw Capital Partners": 8,
    "Gelb Enterprises": 7,
    "Gelson's": 5,
    "Genentech": 9,
    "General Services Administration (GSA)": 205,
    "George Comfort & Sons": 12,
    "George Washington University": 30,
    "Georgetown University": 14,
    "Gilead Sciences": 6,
    "Glendale Unified School District": 25,
    "Global Holdings": 10,
    "Goldman Sachs": 3,
    "Goodwill": 6,
    "Google": 47,
    "Gordon Property Group LLC": 3,
    "Gorjian Real Estate Group": 3,
    "Grainger Industrial Supply": 3,
    "Granite Properties": 3,
    "Greenfield Union School District": 8,
    "Greenlaw Partners": 12,
    "Greystone": 4,
    "Grocery Outlet Bargain Market": 4,
    "Grosvenor": 7,
    "Group Real Estate Development LLC": 6,
    "Grunberg Realty": 3,
    "H&M": 4,
    "HCA Healthcare": 4,
    "HCRE": 4,
    "Habitat For Humanity Restore": 3,
    "Hackman Capital Partners": 4,
    "Hallmark Cards Inc": 3,
    "Handler Real Estate Services": 11,
    "Hankey Investment Company LP": 5,
    "Harbor Group": 5,
    "Harborview Medical Center": 3,
    "Harvard University": 144,
    "Harvest Properties": 12,
    "Hauser & Wirth": 3,
    "Hd Development Of Maryland, INC.": 5,
    "Health Sciences High District": 10,
    "Health Sciences Middle District": 8,
    "Healthcare Realty": 32,
    "Healthpeak Properties": 11,
    "Hearst": 4,
    "Heitman": 5,
    "Heller Properties": 3,
    "Hersha Hospitality Trust": 15,
    "Heskel's Asset Mgmt": 4,
    "Hesperia Unified School District": 12,
    "Hickman Mills C-1": 3,
    "High Tech Elementary Mesa District": 7,
    "Highwoods Properties": 37,
    "Hilson Management Corp.": 12,
    "Hilton": 347,
    "Himmel + Meringoff Properties LLC": 14,
    "Hines": 138,
    "Hive Property Owner LLC": 3,
    "Hobby Lobby": 6,
    "Holy Family University": 3,
    "Homes For The Homeless Institute": 6,
    "Horizon Science Acad-Mckinley Pk": 14,
    "Hospital For Special Surgery": 6,
    "Host Hotels & Resorts": 33,
    "Hotel 21": 4,
    "Howard University": 14,
    "Hudson Pacific Properties": 63,
    "Human Resources Administration": 7,
    "Hyatt": 104,
    "IKEA": 11,
    "IQHQ": 3,
    "Ids Real Estate Group": 13,
    "Illinois Institute Of Technology": 16,
    "Industrious": 9,
    "Inspire Brands": 8,
    "Intel": 3,
    "InterContinental Hotels Group (IHG)": 137,
    "Intercontinental Real Estate": 3,
    "International Bank For Reconstruction & Development": 3,
    "Invesco": 9,
    "Ivy Park": 18,
    "J Street Property Services LLC": 8,
    "J.W. Mays": 3,
    "JBG Smith Properties": 32,
    "JEMB Realty Corporation (JEMB)": 5,
    "JPMorgan Chase (JPM)": 22,
    "Jack Resnick & Sons": 12,
    "Jamaica Hospital": 4,
    "James Campbell Company, LLC": 4,
    "Jamestown L.P.": 34,
    "Jamison Services": 5,
    "Janus Property": 3,
    "Jay Suites": 8,
    "Jcpenney": 56,
    "Jenel Management": 9,
    "Jerome's Furniture & Mattress Store": 4,
    "Jewish Board of Family and Children's Services": 3,
    "Jewish Community Center": 3,
    "Jewish Home And Hospital": 3,
    "John Hancock": 8,
    "Johns Hopkins University": 4,
    "Jones Lang LaSalle (JLL)": 190,
    "Jordache Enterprises": 3,
    "Joseph P. Day": 7,
    "Journey District": 4,
    "Jujamcyn Theaters LLC": 4,
    "Junius Development": 3,
    "Jurupa Unified School District": 5,
    "Justin Management": 10,
    "KBS Realty": 11,
    "KCG Development": 3,
    "KIPP Schools": 13,
    "KKR": 6,
    "KPB Immigration Law Firm": 4,
    "KPMG": 3,
    "Kairos Public School Vacaville Academy District": 4,
    "Kaiser Permanente": 153,
    "Kansas City Public Schools": 39,
    "Kaufman Organization": 45,
    "Keiller Leadership Academy District": 8,
    "Kennedy Wilson": 9,
    "Kerman Unified School District": 5,
    "Kern County": 7,
    "Kern High School District": 12,
    "Kew Mgmt": 5,
    "Kf Braun": 5,
    "Kg Investment Properties": 9,
    "Kiamie Industries": 3,
    "Kidinnu Academy District": 5,
    "Kilroy Realty": 97,
    "Kimberly Holdings, LLC": 3,
    "Kimco Realty Corporation": 12,
    "King County": 4,
    "King Terminal LLC Mass LLC": 6,
    "King-Chavez Academy Of Excellence District": 8,
    "Kings Canyon Joint Unified School District": 4,
    "Kings County": 4,
    "Knotel": 5,
    "Koeppel Rosen": 17,
    "Kohl's": 50,
    "Korea Investment Corporation": 3,
    "Kroger": 105,
    "L&L Holding": 10,
    "LBA Realty": 8,
    "LUMA Hotel": 3,
    "LVMH Moet Hennessy Louis Vuitton (LVMH)": 3,
    "La Caisse": 4,
    "La Salle University": 3,
    "Lake Realty Management LLC": 4,
    "Lam Research": 3,
    "Latin School Of Chicago": 3,
    "Lawrence Group": 4,
    "Leadership Military Academy - Indio District": 6,
    "Lebeau Realty & Associates": 6,
    "Lee & Associates": 9,
    "Lefrak": 4,
    "Legend Real Estate Management": 3,
    "Lesley University": 4,
    "Lincoln Property Company": 132,
    "Living Spaces": 8,
    "Lodi Unified School District": 6,
    "Loews Hotels": 9,
    "Loma Linda University": 10,
    "Long Beach Unified School District": 67,
    "Longwood Management": 3,
    "Los Angeles County": 22,
    "Los Angeles Unified School District": 12,
    "Los Angeles World Airports": 15,
    "Los Banos Unified School District": 3,
    "Lowe's": 55,
    "Lsl Advisors": 10,
    "Lucky": 5,
    "MCR Hotels": 3,
    "MD Carlisle": 3,
    "MGR Holdings, LLC": 8,
    "MHF": 4,
    "MJ Orbach": 4,
    "MRP Realty": 11,
    "MacTaggart Family": 3,
    "Macerich": 14,
    "Macklowe Management": 5,
    "Macy's": 97,
    "Madera Unified School District": 8,
    "Magnolia Science Academy San Diego District": 4,
    "Maimonides Medical Center": 4,
    "Manhattan College": 4,
    "Manova Partners Inc.": 5,
    "Manulife": 7,
    "Marc Realty": 16,
    "Marin County": 3,
    "Marriott": 521,
    "Marx Realty": 5,
    "Marysville Joint Unified School District": 4,
    "Massachusetts Institute Of Technology": 83,
    "Matern Law Group, PC": 3,
    "Mather": 4,
    "McDonald's": 3,
    "McKinsey & Company": 4,
    "McKinstry": 3,
    "Meadow Partners": 6,
    "Medtronic, INC.": 3,
    "Mehra Properties Inc.": 6,
    "Memorial Sloan Kettering Cancer Center": 4,
    "MemorialCare Health System": 8,
    "Menifee Union School District": 4,
    "Menlo Equities": 3,
    "Merrill Gardens": 11,
    "MetLife": 13,
    "Meta": 9,
    "Meyer Equities": 3,
    "Michaels": 6,
    "Microsoft": 11,
    "Miracosta College": 3,
    "Mitsui Fudosan America": 6,
    "Mmc Corporation": 3,
    "Modesto City Schools": 11,
    "Moinian Group": 13,
    "Mojave River Academy": 6,
    "Monarchs Sub, LLC": 4,
    "Montague-Lee Limited Partnership": 3,
    "Montefiore Medical Center": 8,
    "Moreno Valley Unified School District": 19,
    "Morgan Stanley": 5,
    "Motel 6": 10,
    "Mount Sinai Health System": 8,
    "Mountain View Elementary School District": 7,
    "Mourier Land Investment Corporation": 10,
    "Multi-Employer Property Trust (MEPT)": 3,
    "Multnomah County": 6,
    "Munich Re": 4,
    "Museum Of Fine Arts": 3,
    "NAI Global": 15,
    "NVIDIA": 3,
    "Napa County": 4,
    "National Collegiate Preparatory Pchs": 11,
    "National Community Reinvestment Coalition": 3,
    "National University": 7,
    "Neiman Marcus": 4,
    "NetApp": 6,
    "Netflix": 6,
    "New England Conservatory Of Music": 4,
    "New Seasons Market": 7,
    "New York City Geographic District": 15,
    "New York Law School": 3,
    "New York Life Insurance Company": 19,
    "New York Public Library": 8,
    "New York University (NYU)": 49,
    "New York-Presbyterian Hospital": 5,
    "Newmark": 134,
    "Newport Healthcare Center, LLC": 3,
    "Nextplay Consulting LLC": 5,
    "Nicotra Group": 5,
    "Nike": 4,
    "Nokia": 3,
    "Nordstrom": 25,
    "Norges Bank Investment Management": 8,
    "North American Properties": 3,
    "North Side Community School": 3,
    "Northbay Health": 4,
    "Northeastern Illinois University": 5,
    "Northeastern University": 22,
    "Northern Star LLC": 4,
    "Northern Trust": 7,
    "Northwestern Memorial Hospital": 5,
    "Northwestern Mutual": 3,
    "Northwestern University": 7,
    "Northwood Investors": 8,
    "Oakmont Senior Living": 32,
    "Ocean View": 4,
    "Ocean West Management Services": 5,
    "Oceanside Unified School District": 12,
    "Office Depot/Officemax": 4,
    "Office Properties Income Trust": 29,
    "Okada & Company": 18,
    "Olmstead Properties": 19,
    "Omega Healthcare Investors": 6,
    "Omni Hotel": 10,
    "Onni Group": 8,
    "Options For Youth-Acton District": 6,
    "Oracle": 15,
    "Orange County": 10,
    "Orchard Commercial, INC.": 4,
    "Oxford Preparatory Academy": 8,
    "Oxford Properties Group": 8,
    "Oyster-Adams Bilingual School (Adams)": 4,
    "PM Realty Group": 3,
    "PNC Bank": 5,
    "PRD Realty": 4,
    "PSP Investments": 6,
    "Pace University": 3,
    "Pacific Union Elementary School District": 4,
    "Pali Management Group": 3,
    "Parallel Capital Partners": 3,
    "Paramount Group": 40,
    "Paramount Studios": 7,
    "Park Hill R-5 School District": 13,
    "Park Hotels & Resorts": 15,
    "Partnership Healthplan Of California": 3,
    "Patterson Joint Unified School District": 4,
    "Pembroke": 5,
    "Pendry Hotels": 3,
    "Pendulum Property Partners": 4,
    "Penumbra": 4,
    "Petco": 7,
    "Pete's Fresh Market": 3,
    "Philadelphia County": 13,
    "Philadelphia University": 4,
    "Physicians Medical Center": 4,
    "Piedmont Office Realty Trust": 16,
    "Pih Health": 10,
    "Pittsburg Unified School District": 12,
    "Pixar": 3,
    "Placer County": 3,
    "Planned Parenthood": 4,
    "Pleasanton Unified School District": 4,
    "Plumas Lake Elementary (Olivehurst)": 3,
    "Point West Office Investors, LLC": 5,
    "Polinger Co. - 2401 Pennsylvania Avenue Residences": 3,
    "Pontegadea": 7,
    "Port Authority Of Kcmo": 5,
    "Port Of Seattle": 8,
    "Portland Community College": 13,
    "Portland State University": 6,
    "Potomac Investment Properties": 4,
    "Pratt Institute": 8,
    "Prime Healthcare Services": 15,
    "Princeton International Properties": 4,
    "Principal Real Estate Investors": 79,
    "Progressive Insurance": 5,
    "Property Group Partners": 4,
    "Prospect Health System": 11,
    "Providence Health": 38,
    "Publix": 3,
    "PwC": 3,
    "Pyrus Management LLC": 5,
    "Quadrangle Management Company": 5,
    "Qualcomm": 7,
    "Quartermaster Plaza 1777 LLC": 3,
    "Quest Diagnostics": 3,
    "RFR Realty": 20,
    "RLJ Lodging Trust": 11,
    "RNM Properties": 3,
    "RXR Realty": 14,
    "Raber Enterprises": 3,
    "Rainier Valley Leadership Academy": 13,
    "Raintree Realty II, LLC": 5,
    "Raley's": 7,
    "Ranken Technical College": 4,
    "Realty Income Corporation": 3,
    "Rebel Hospitality": 7,
    "Redcar Properties LTD": 5,
    "Regal Entertainment": 14,
    "Regus": 9,
    "Related Companies": 22,
    "Renaissance Properties": 5,
    "Republic Properties Corporation": 3,
    "Resolution Real Estate": 21,
    "Restaurant Depot": 14,
    "Restoration Hardware": 4,
    "Rexford Industrial": 3,
    "Rialto Unified School District": 10,
    "Rising Realty Partners": 7,
    "Rite Aid": 3,
    "RiverRock Real Estate Group": 3,
    "Riverdale Country School (New York)": 3,
    "Riverside Community College District": 3,
    "Riverside County": 17,
    "Riverside Unified School District": 19,
    "Robertson Properties Group": 4,
    "Rocco Tomassetti": 3,
    "Rockefeller Group": 3,
    "Rockhill Management, L.L.C.": 10,
    "Rockhurst University": 4,
    "Rockpoint Group": 6,
    "Rockrose Development": 9,
    "Rockwood Capital": 8,
    "Roman Catholic Archdiocese Of Washington": 3,
    "Roman Catholic Church": 35,
    "Ronald McDonald House Charities": 4,
    "Room & Board": 3,
    "Roosevelt Lee": 3,
    "Rosen Equities": 23,
    "Roseville Joint Union High School District": 4,
    "Ross Stores": 37,
    "Rubicon Point Partners": 4,
    "Rudin Management Co. Inc.": 14,
    "Rush University Medical Center (RUMC)": 3,
    "S.C. Herman & Associates, Inc.": 4,
    "SEPHORA": 3,
    "SL Green": 52,
    "SSM Health": 3,
    "Sacramento City Unified School District": 22,
    "Sacramento County": 6,
    "Saddleback Valley Unified School District": 6,
    "Safety Training Seminars": 3,
    "Sage Realty": 6,
    "Saks Fifth Avenue": 4,
    "Salesforce": 3,
    "Samco Properties": 13,
    "Samson": 4,
    "San Antonio Regional Hospital": 3,
    "San Bernardino City Unified School District": 26,
    "San Bernardino Community College District": 3,
    "San Bernardino County": 5,
    "San Diego Gas & Electric": 3,
    "San Diego Unified School District": 63,
    "San Jacinto Unified School District": 10,
    "San Jose City College": 3,
    "San Jose Unified School District": 3,
    "San Juan Unified School District": 20,
    "San Lorenzo Unified School District": 4,
    "San Marcos Unified School District": 6,
    "San Mateo Union High School District": 3,
    "San Pasqual Union Elementary School District": 4,
    "Sanger Unified School District": 5,
    "Santa Clara County": 4,
    "Santa Clara Unified School District": 5,
    "Santa Maria Joint Union High School District": 5,
    "Santa Monica College": 4,
    "Santa Monica-Malibu Unified School District": 7,
    "Santa Rosa City Schools": 7,
    "Santee School District": 8,
    "Sapir Organization": 4,
    "Savanna Real Estate": 12,
    "Savannah College Of Art And Design": 3,
    "Savitt Partners": 9,
    "Schnucks": 3,
    "School District of Philadelphia": 26,
    "School Of The Art Institute Of Chicago": 3,
    "Schoolsfirst Federal Credit Union": 5,
    "Schur Management Company": 3,
    "Scientific Games": 3,
    "Scripps Health": 18,
    "Sears": 20,
    "Seattle Cancer Care Alliance": 3,
    "Seattle Central College": 9,
    "Seattle Children's Hospital": 4,
    "Seattle Public Schools": 82,
    "Senior Suites": 20,
    "Service Properties Trust": 7,
    "Sharp HealthCare": 14,
    "ShopRite": 5,
    "Shorenstein Properties": 37,
    "Shriners Hospitals For Children": 6,
    "Shubert Theatre": 7,
    "Shulsky Properties": 4,
    "Sierra Pacific Properties": 3,
    "Silk And Halpern": 3,
    "Silver Cloud Inn": 5,
    "Silvercup Studios": 4,
    "Silvergate Residential Care": 3,
    "Silverstein Properties": 8,
    "Simmons University": 9,
    "Simon Property Group": 6,
    "Sinvin": 5,
    "Sioni Group": 9,
    "Smart & Final": 12,
    "Snowflake": 3,
    "Sobrato Organization": 4,
    "Social Security Administration": 5,
    "Sol Vista": 5,
    "Solil Management": 3,
    "Soloviev Group": 6,
    "Sonesta International Hotels": 44,
    "Sony": 3,
    "South Seattle College": 7,
    "Southeastern Pennsylvania Transportation Authority (SEPTA)": 4,
    "Southern California Edison": 13,
    "Southern Company": 3,
    "Sovereign Partners": 5,
    "Spaces": 6,
    "Spar Knitwear CORP": 3,
    "Spear Street Capital": 5,
    "Spectrum Properties Group Inc.": 9,
    "Spirit Halloween": 3,
    "Sprouts Farmers Market": 11,
    "St Jude Medical Center": 3,
    "St. John's Place Family Center": 3,
    "St. John's University": 4,
    "St. Louis Public Schools": 17,
    "St. Luke's Hospital": 6,
    "Stahl Organization": 6,
    "Stanford University": 26,
    "Starpointe Management LLC": 3,
    "Stars REI": 4,
    "Starwood Capital": 6,
    "State Farm": 11,
    "State Of New York": 32,
    "State Of Oregon": 3,
    "State Of Washington": 3,
    "State Street": 5,
    "State of California": 60,
    "Staten Island University Hospital": 3,
    "Stater Bros. Markets": 4,
    "Stawski Partners": 7,
    "Steel Equities": 5,
    "Steelwave": 11,
    "Steinberg": 3,
    "Stellar Management": 8,
    "Stephens Institute": 6,
    "Sterling Bay": 4,
    "Stockton Unified School District": 8,
    "Stoladi Property Group, Inc.": 8,
    "Stonebridge": 5,
    "Stony Point East LP": 3,
    "Stout & Teague Companies": 4,
    "Stream Realty Partners": 11,
    "Suffolk University": 3,
    "Sulphur Springs Union School District": 3,
    "Summit Hotel Properties": 13,
    "Summit Public Schools": 6,
    "Sundale Union Elementary School District": 5,
    "Sunrise Senior Living": 32,
    "Sunset Development Company": 19,
    "Sutter Health": 45,
    "Swedish Medical Center": 3,
    "Swift Real Estate Partners": 24,
    "Swig Company": 15,
    "Sycamore Academy Of Science And Cultural Arts Chino Vly District": 3,
    "Symantec Corporation": 6,
    "Synergy Investments": 8,
    "T-Mobile": 3,
    "T. Rowe Price": 3,
    "TA Realty": 13,
    "TD Bank": 3,
    "TF Cornerstone Inc.": 16,
    "TIAA": 15,
    "TJX Companies": 13,
    "TMG Partners": 5,
    "TMT Development": 3,
    "Taconic Partners": 4,
    "Target": 301,
    "Temecula Valley Unified School District": 26,
    "Temple University": 33,
    "Terreno Realty": 5,
    "Tesla": 3,
    "The 58-64 40 St. Corp., Inc": 3,
    "The Arch Community School": 5,
    "The Ashtin Group, Inc.": 3,
    "The Biome": 3,
    "The Davis Companies": 5,
    "The Doyle Collection": 4,
    "The Durst Organization": 20,
    "The Education Corps District": 3,
    "The Eric Ryan Corporation": 7,
    "The Evergreen Company": 8,
    "The Home Depot": 230,
    "The Irvine Company": 163,
    "The John Buck Company": 4,
    "The Lenkin Company": 12,
    "The Meridian Group": 4,
    "The Muller Company": 8,
    "The New School": 7,
    "The Pacifica Company, LP.": 6,
    "The Philadelphia Cs For Arts And Sciences At Hr Edmunds": 4,
    "The RMR Group": 16,
    "The Salvation Army": 19,
    "The Soulard School": 4,
    "The Tower Companies": 5,
    "Thomas Jefferson University": 9,
    "Thor Equities": 9,
    "Tiarna Real Estate Services": 6,
    "Time Equities": 3,
    "Tishman Speyer": 64,
    "Tpp-Lpw Som Property LLC": 3,
    "Transwestern": 43,
    "Travis Unified School District": 5,
    "Tri City Acquisitions": 4,
    "Triad Management Systems INC.": 3,
    "Triangle Assets": 8,
    "Trigon Equities": 3,
    "Trinity Church": 12,
    "Trinity Real Estate": 6,
    "Triumph Hotels": 9,
    "Truist": 8,
    "Truman Medical Center": 3,
    "Trump Organization": 6,
    "Tufts University": 4,
    "Turner Broadcasting": 3,
    "Twin Rivers Unified School District": 6,
    "Two Trees Management": 4,
    "UBS": 5,
    "UMB Bank": 3,
    "UNIZO Holdings": 6,
    "US Bank": 7,
    "US. Federal Government": 8,
    "USAA Real Estate": 5,
    "Uci Health": 8,
    "Unibail-Rodamco-Westfield": 7,
    "Unico Properties": 22,
    "Union Investment Real Estate GmbH": 8,
    "Unire Real Estate Group": 3,
    "United Cerebral Palsy Of New York City": 3,
    "United Talmudical Academy (New York)": 9,
    "United Way": 3,
    "Unity Health Care": 3,
    "University Of Chicago": 13,
    "University Of Denver": 17,
    "University Of Pennsylvania": 8,
    "University Of Portland": 4,
    "University Of San Francisco": 11,
    "University Of Southern California": 29,
    "University Of The District Of Columbia": 4,
    "University of California": 35,
    "University of Illinois Foundation": 3,
    "University of Washington (UW)": 5,
    "Urban Innovations": 4,
    "Urban Outfitters": 3,
    "Urban Renaissance Group": 7,
    "VMware": 13,
    "Vacaville Unified School District": 4,
    "Valencia College": 8,
    "Vallarta Supermarkets": 7,
    "Vanbarton Group": 14,
    "Various Tenants": 4,
    "Ventas": 52,
    "Vert Energy Group": 5,
    "Virginia Mason": 6,
    "Visa": 4,
    "Visalia Unified School District": 24,
    "Vision Quest & Career Pathway District": 3,
    "Voices College-Bound Language Acad At Mt. Pleasant District": 4,
    "Vornado Realty Trust": 77,
    "WC Smith": 3,
    "WFG National Title Insurance Company": 4,
    "WMC Associates": 5,
    "Walgreens": 15,
    "Walmart": 285,
    "Walt Disney Imagineering": 12,
    "Walter & Samuels": 14,
    "Warner Bros Discovery": 9,
    "Washington Hospital Healthcare": 5,
    "Washington Metropolitan Area Transit Authority": 10,
    "Washington Unified School District": 5,
    "Washington University in St. Louis": 5,
    "Waterman Properties": 7,
    "Waverly Management": 3,
    "Wells Fargo": 12,
    "Welltower": 48,
    "Wentworth Institute Of Technology": 10,
    "Wespac Management Group, INC": 3,
    "West Coast University": 4,
    "West Contra Costa Unified School District": 6,
    "Western University Of Health Sciences": 4,
    "Westlake Park Place Inc.": 3,
    "Westminster": 3,
    "Westside Union Elementary School District": 7,
    "Wework": 27,
    "Wharton Properties": 3,
    "Wildflower Open Classroom District": 5,
    "Willco Companies": 5,
    "William S. Hart Union High School District": 10,
    "Williams Equities": 25,
    "Winco Foods": 24,
    "Windsor Mgmt": 6,
    "Windsor Unified School District": 3,
    "Winoker Realty": 4,
    "Winter Organization": 10,
    "Workday": 3,
    "Worthe Real Estate": 11,
    "Wyndham": 75,
    "YOTEL": 3,
    "Yellowstone Real Estate": 4,
    "Yeshiva University": 8,
    "Young Men's Christian Association (YMCA)": 8,
    "Yuba City Unified School District": 3,
    "Zeller": 3,
    "Zuckerman Gravely Management": 27,
}
